In [2]:

from pathlib import Path
import pandas as pd
import numpy as np

# ============================================================
# RF124_leaf16 — Reconstrucción desde fuentes oficiales
# Celda 1: auditoría de entradas
# ============================================================

ROOT = Path.cwd().resolve()

if ROOT.name == "notebooks":
    ROOT = ROOT.parent
else:
    candidatos = [ROOT, *ROOT.parents]
    ROOT = next(
        (
            p for p in candidatos
            if p.name == "AgroCebada-FIRA-2026"
            and (p / "data" / "raw" / "tabular").is_dir()
        ),
        ROOT
    )

RAW_DIR = ROOT / "data" / "raw" / "tabular"

FUENTES_OFICIALES = {
    "BASICO": RAW_DIR / "Conjunto_datos_BASICO_AgroCebada2026.csv",
    "PRO": RAW_DIR / "Conjunto_datos_PRO_AgroCebada.csv",
    "ID_RENDIMIENTO": RAW_DIR / "ID_area_rendimiento_70_30_Reto_AgroCebada.csv",
}

print("Raíz del proyecto:", ROOT)
print("Directorio de fuentes oficiales:", RAW_DIR)

for nombre, ruta in FUENTES_OFICIALES.items():
    if not ruta.is_file():
        raise FileNotFoundError(
            f"No se encontró la fuente oficial {nombre}: {ruta}"
        )

# Lectura de las fuentes oficiales originales.
datos_oficiales = {
    nombre: pd.read_csv(ruta)
    for nombre, ruta in FUENTES_OFICIALES.items()
}

for nombre, df in datos_oficiales.items():
    print("\n" + "=" * 80)
    print(f"FUENTE: {nombre}")
    print("Archivo:", FUENTES_OFICIALES[nombre].name)
    print("Dimensiones:", df.shape)

    print("\nColumnas y tipos:")
    display(
        pd.DataFrame({
            "columna": df.columns,
            "tipo": [str(t) for t in df.dtypes],
            "nulos": df.isna().sum().values,
            "n_unicos": df.nunique(dropna=True).values,
        })
    )

    print("\nPrimeras 5 filas:")
    display(df.head())

    print("\nFilas duplicadas completas:", int(df.duplicated().sum()))

Raíz del proyecto: C:\Users\nonoe\OneDrive\Escritorio\Proyectos\AgroCebada-FIRA-2026
Directorio de fuentes oficiales: C:\Users\nonoe\OneDrive\Escritorio\Proyectos\AgroCebada-FIRA-2026\data\raw\tabular

================================================================================
FUENTE: BASICO
Archivo: Conjunto_datos_BASICO_AgroCebada2026.csv
Dimensiones: (107666, 96)

Columnas y tipos:

                 columna     tipo  nulos  n_unicos
0            ID_POLIGONO      str      0       197
1          fecha_captura      str      0       608
2                 sensor      str      0         2
3          ndvi_promedio  float64  62789       842
4               ndvi_std  float64  62789       215
..                   ...      ...    ...       ...
91        enddi_promedio  float64  62789       411
92             enddi_std  float64  62789       115
93             enddi_max  float64  62789       487
94             enddi_min  float64  62789       416
95  porcentaje_nubosidad  float64   3056      9176

[96 rows x 4 columns]

Primeras 5 filas:

,ID_POLIGONO,fecha_captura,sensor,ndvi_promedio,ndvi_std,ndvi_max,ndvi_min,evi_promedio,evi_std,evi_max,...,dswi5_min,nddi_promedio,nddi_std,nddi_max,nddi_min,enddi_promedio,enddi_std,enddi_max,enddi_min,porcentaje_nubosidad
0,AGC_011,20/04/2022,Landsat,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0
1,AGC_011,16/03/2024,Landsat,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0
2,AGC_011,15/03/2024,Landsat,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0
3,AGC_011,26/08/2025,Landsat,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0
4,AGC_011,10/03/2025,Landsat,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0

Filas duplicadas completas: 0

================================================================================
FUENTE: PRO
Archivo: Conjunto_datos_PRO_AgroCebada.csv
Dimensiones: (47804, 20)

Columnas y tipos:

                 columna     tipo  nulos  n_unicos
0            ID_POLIGONO      str      0       197
1          fecha_captura      str      0       311
2                 sensor      str      0         1
3          ndvi_promedio  float64  12057       778
4               ndvi_std  float64  12057       217
5               ndvi_max  float64  12057       774
6               ndvi_min  float64  12057       868
7           evi_promedio  float64  12057       687
8                evi_std  float64  12057       193
9                evi_max  float64  12057       815
10               evi_min  float64  12057       631
11          lai_promedio  float64  12057      2753
12               lai_std  float64  12057       689
13               lai_max  float64  12057      2959
14               lai_min  float64  12057      2523
15        msavi_promedio  float64  12057       683
16             msavi_std  float64  12057       198
17             msavi_max  float64  12057       787
18             msavi_min  float64  12057       586
19  porcentaje_nubosidad  float64      0      5064

Primeras 5 filas:

,ID_POLIGONO,fecha_captura,sensor,ndvi_promedio,ndvi_std,ndvi_max,ndvi_min,evi_promedio,evi_std,evi_max,evi_min,lai_promedio,lai_std,lai_max,lai_min,msavi_promedio,msavi_std,msavi_max,msavi_min,porcentaje_nubosidad
0,AGC_056,05/02/2025,Planet,0.300,0.042,0.553,0.175,0.138,0.022,0.251,0.068,1.049,0.182,2.144,0.586,0.135,0.022,0.244,0.066,0.0
1,AGC_056,08/02/2025,Planet,0.204,0.043,0.529,0.125,0.110,0.018,0.209,0.074,0.697,0.167,1.888,0.247,0.110,0.018,0.207,0.072,0.0
2,AGC_056,07/02/2025,Planet,0.241,0.043,0.534,0.154,0.134,0.018,0.224,0.098,0.826,0.159,1.858,0.404,0.135,0.018,0.230,0.098,0.0
3,AGC_056,09/02/2025,Planet,0.246,0.039,0.536,0.153,0.142,0.018,0.243,0.098,0.818,0.159,1.849,0.399,0.141,0.018,0.237,0.095,0.0
4,AGC_056,30/01/2025,Planet,0.211,0.046,0.533,0.113,0.110,0.020,0.229,0.069,0.724,0.187,1.955,0.277,0.111,0.021,0.230,0.067,0.0

Filas duplicadas completas: 0

================================================================================
FUENTE: ID_RENDIMIENTO
Archivo: ID_area_rendimiento_70_30_Reto_AgroCebada.csv
Dimensiones: (197, 5)

Columnas y tipos:

            columna     tipo  nulos  n_unicos
0       ID_POLIGONO      str      0       197
1           AREA_HA  float64      0       175
2  RENDIMIENTO_T_HA  float64     59        67
3          CONJUNTO      str      0         2
4        Unnamed: 4  float64    197         0

Primeras 5 filas:

  ID_POLIGONO  AREA_HA  RENDIMIENTO_T_HA       CONJUNTO  Unnamed: 4
0     AGC_001     7.61              3.50  ENTRENAMIENTO         NaN
1     AGC_002     2.31              4.63  ENTRENAMIENTO         NaN
2     AGC_003    18.68               NaN     PREDICCION         NaN
3     AGC_004     8.00              3.00  ENTRENAMIENTO         NaN
4     AGC_005     2.27              5.16  ENTRENAMIENTO         NaN

Filas duplicadas completas: 0

In [3]:

# ============================================================
# Celda 2 — Auditoría temporal y estructural de fuentes oficiales
# No modifica archivos ni construye todavía el dataset de modelado.
# ============================================================

basico = datos_oficiales["BASICO"].copy()
pro = datos_oficiales["PRO"].copy()
etiquetas = datos_oficiales["ID_RENDIMIENTO"].copy()

for nombre, df in [("BASICO", basico), ("PRO", pro)]:
    print("\n" + "=" * 80)
    print(f"{nombre}: FECHAS, SENSORES Y OBSERVACIONES")

    fechas = pd.to_datetime(
        df["fecha_captura"],
        dayfirst=True,
        errors="coerce"
    )

    print("Fechas no interpretables:", int(fechas.isna().sum()))
    print("Primera fecha:", fechas.min())
    print("Última fecha:", fechas.max())

    print("\nObservaciones por sensor:")
    print(df["sensor"].value_counts(dropna=False))

    print("\nNúmero de fechas distintas:")
    print(fechas.nunique())

    print("\nObservaciones por parcela — resumen:")
    print(
        df.groupby("ID_POLIGONO")
        .size()
        .describe()
        .round(2)
    )

    print("\nColumnas:")
    print(df.columns.tolist())


print("ETIQUETAS OFICIALES")

print(etiquetas["CONJUNTO"].value_counts(dropna=False))
print("\nRendimiento por conjunto:")
print(
    etiquetas.groupby("CONJUNTO")["RENDIMIENTO_T_HA"]
    .agg(["count", "mean", "std", "min", "max"])
)

# Comprobar si PRO comparte las mismas columnas que BASICO,
# sin asumir que sea correcto concatenarlos.

print("RELACIÓN ENTRE COLUMNAS")

columnas_basico = set(basico.columns)
columnas_pro = set(pro.columns)

print("Columnas compartidas:", len(columnas_basico & columnas_pro))
print("Solo en BASICO:", sorted(columnas_basico - columnas_pro))
print("Solo en PRO:", sorted(columnas_pro - columnas_basico))

# Comprobar cobertura de identificadores.
ids_etiquetas = set(etiquetas["ID_POLIGONO"])
ids_basico = set(basico["ID_POLIGONO"])
ids_pro = set(pro["ID_POLIGONO"])

print("\nCobertura de parcelas:")
print("IDs oficiales:", len(ids_etiquetas))
print("IDs presentes en BASICO:", len(ids_etiquetas & ids_basico))
print("IDs presentes en PRO:", len(ids_etiquetas & ids_pro))
print("IDs oficiales ausentes de BASICO:", sorted(ids_etiquetas - ids_basico))
print("IDs oficiales ausentes de PRO:", sorted(ids_etiquetas - ids_pro))

================================================================================
BASICO: FECHAS, SENSORES Y OBSERVACIONES
Fechas no interpretables: 0
Primera fecha: 2022-01-01 00:00:00
Última fecha: 2025-12-31 00:00:00

Observaciones por sensor:
sensor
Sentinel-2    59040
Landsat       48626
Name: count, dtype: int64

Número de fechas distintas:
608

Observaciones por parcela — resumen:
count    197.00
mean     546.53
std       65.28
min      494.00
25%      504.00
50%      511.00
75%      573.00
max      692.00
dtype: float64

Columnas:
['ID_POLIGONO', 'fecha_captura', 'sensor', 'ndvi_promedio', 'ndvi_std', 'ndvi_max', 'ndvi_min', 'evi_promedio', 'evi_std', 'evi_max', 'evi_min', 'crc_promedio', 'crc_std', 'crc_max', 'crc_min', 'mcrc_promedio', 'mcrc_std', 'mcrc_max', 'mcrc_min', 'ndsvi_promedio', 'ndsvi_std', 'ndsvi_max', 'ndsvi_min', 'srndi_promedio', 'srndi_std', 'srndi_max', 'srndi_min', 'mra_promedio', 'mra_std', 'mra_max', 'mra_min', 'lai_promedio', 'lai_std', 'lai_max', 'lai_min', 'fapar_promedio', 'fapar_std', 'fapar_max', 'fapar_min', 'savi_promedio', 'savi_std', 'savi_max', 'savi_min', 'vi6t_promedio', 'vi6t_std', 'vi6t_max', 'vi6t_min', 'ndti_promedio', 'ndti_std', 'ndti_max', 'ndti_min', 'sti_promedio', 'sti_std', 'sti_max', 'sti_min', 'ndwi_promedio', 'ndwi_std', 'ndwi_max', 'ndwi_min', 'endwi_promedio', 'endwi_std', 'endwi_max', 'endwi_min', 'msi_promedio', 'msi_std', 'msi_max', 'msi_min', 'emsi_promedio', 'emsi_std', 'emsi_max', 'emsi_min', 'dswi2_promedio', 'dswi2_std', 'dswi2_max', 'dswi2_min', 'dswi3_promedio', 'dswi3_std', 'dswi3_max', 'dswi3_min', 'dswi4_promedio', 'dswi4_std', 'dswi4_max', 'dswi4_min', 'dswi5_promedio', 'dswi5_std', 'dswi5_max', 'dswi5_min', 'nddi_promedio', 'nddi_std', 'nddi_max', 'nddi_min', 'enddi_promedio', 'enddi_std', 'enddi_max', 'enddi_min', 'porcentaje_nubosidad']

================================================================================
PRO: FECHAS, SENSORES Y OBSERVACIONES
Fechas no interpretables: 0
Primera fecha: 2025-01-01 00:00:00
Última fecha: 2025-12-30 00:00:00

Observaciones por sensor:
sensor
Planet    47804
Name: count, dtype: int64

Número de fechas distintas:
311

Observaciones por parcela — resumen:
count    197.00
mean     242.66
std        4.42
min      233.00
25%      240.00
50%      243.00
75%      246.00
max      251.00
dtype: float64

Columnas:
['ID_POLIGONO', 'fecha_captura', 'sensor', 'ndvi_promedio', 'ndvi_std', 'ndvi_max', 'ndvi_min', 'evi_promedio', 'evi_std', 'evi_max', 'evi_min', 'lai_promedio', 'lai_std', 'lai_max', 'lai_min', 'msavi_promedio', 'msavi_std', 'msavi_max', 'msavi_min', 'porcentaje_nubosidad']
ETIQUETAS OFICIALES
CONJUNTO
ENTRENAMIENTO    138
PREDICCION        59
Name: count, dtype: int64

Rendimiento por conjunto:
               count      mean       std  min   max
CONJUNTO
ENTRENAMIENTO    138  3.955362  0.851161  2.0  5.59
PREDICCION         0       NaN       NaN  NaN   NaN
RELACIÓN ENTRE COLUMNAS
Columnas compartidas: 16
Solo en BASICO: ['crc_max', 'crc_min', 'crc_promedio', 'crc_std', 'dswi2_max', 'dswi2_min', 'dswi2_promedio', 'dswi2_std', 'dswi3_max', 'dswi3_min', 'dswi3_promedio', 'dswi3_std', 'dswi4_max', 'dswi4_min', 'dswi4_promedio', 'dswi4_std', 'dswi5_max', 'dswi5_min', 'dswi5_promedio', 'dswi5_std', 'emsi_max', 'emsi_min', 'emsi_promedio', 'emsi_std', 'enddi_max', 'enddi_min', 'enddi_promedio', 'enddi_std', 'endwi_max', 'endwi_min', 'endwi_promedio', 'endwi_std', 'fapar_max', 'fapar_min', 'fapar_promedio', 'fapar_std', 'mcrc_max', 'mcrc_min', 'mcrc_promedio', 'mcrc_std', 'mra_max', 'mra_min', 'mra_promedio', 'mra_std', 'msi_max', 'msi_min', 'msi_promedio', 'msi_std', 'nddi_max', 'nddi_min', 'nddi_promedio', 'nddi_std', 'ndsvi_max', 'ndsvi_min', 'ndsvi_promedio', 'ndsvi_std', 'ndti_max', 'ndti_min', 'ndti_promedio', 'ndti_std', 'ndwi_max', 'ndwi_min', 'ndwi_promedio', 'ndwi_std', 'savi_max', 'savi_min', 'savi_promedio', 'savi_std', 'srndi_max', 'srndi_min', 'srndi_promedio', 'srndi_std', 'sti_max', 'sti_min', 'sti_promedio', 'sti_std', 'vi6t_max', 'vi6t_min', 'vi6t_promedio', 'vi6t_std']
Solo en PRO: ['msavi_max', 'msavi_min', 'msavi_promedio', 'msavi_std']

Cobertura de parcelas:
IDs oficiales: 197
IDs presentes en BASICO: 197
IDs presentes en PRO: 197
IDs oficiales ausentes de BASICO: []
IDs oficiales ausentes de PRO: []

In [4]:
# CELDA 3. Diagnóstico de disponibilidad de variables satelitales

import pandas as pd
import numpy as np

for nombre in ["BASICO", "PRO"]:
    df = datos_oficiales[nombre].copy()

    df["fecha_captura"] = pd.to_datetime(
        df["fecha_captura"],
        dayfirst=True,
        errors="coerce"
    )

    columnas_id = ["ID_POLIGONO", "fecha_captura", "sensor"]
    columnas_variables = [
        c for c in df.columns
        if c not in columnas_id
        and c != "porcentaje_nubosidad"
        and pd.api.types.is_numeric_dtype(df[c])
    ]

    print(f"\nDiagnóstico: {nombre}")
    print(f"Registros: {len(df):,}")
    print(f"Variables numéricas analizadas: {len(columnas_variables)}")

    # Porcentaje de valores faltantes por variable
    faltantes = (
        df[columnas_variables]
        .isna()
        .mean()
        .mul(100)
        .sort_values(ascending=False)
    )

    print("\nPorcentaje de valores faltantes por variable:")
    display(faltantes.to_frame("faltantes_pct").round(2))

    # Cobertura por sensor
    print("\nDisponibilidad por sensor:")
    resumen_sensor = (
        df.groupby("sensor")[columnas_variables]
        .agg(lambda s: s.notna().mean() * 100)
        .T
    )
    display(resumen_sensor.round(2))

    # Cobertura por año
    df["ANIO"] = df["fecha_captura"].dt.year

    print("\nDisponibilidad por año:")
    resumen_anio = (
        df.groupby("ANIO")[columnas_variables]
        .agg(lambda s: s.notna().mean() * 100)
        .T
    )
    display(resumen_anio.round(2))

Diagnóstico: BASICO
Registros: 107,666
Variables numéricas analizadas: 92

Porcentaje de valores faltantes por variable:

                faltantes_pct
vi6t_min                71.16
vi6t_max                71.16
vi6t_std                71.16
vi6t_promedio           71.16
fapar_promedio          58.32
...                       ...
nddi_min                58.32
enddi_promedio          58.32
enddi_std               58.32
enddi_max               58.32
enddi_min               58.32

[92 rows x 1 columns]

Disponibilidad por sensor:

sensor          Landsat  Sentinel-2
ndvi_promedio       0.0       76.01
ndvi_std            0.0       76.01
ndvi_max            0.0       76.01
ndvi_min            0.0       76.01
evi_promedio        0.0       76.01
...                 ...         ...
nddi_min            0.0       76.01
enddi_promedio      0.0       76.01
enddi_std           0.0       76.01
enddi_max           0.0       76.01
enddi_min           0.0       76.01

[92 rows x 2 columns]

Disponibilidad por año:

ANIO             2022   2023   2024   2025
ndvi_promedio   37.58  38.09  43.76  47.16
ndvi_std        37.58  38.09  43.76  47.16
ndvi_max        37.58  38.09  43.76  47.16
ndvi_min        37.58  38.09  43.76  47.16
evi_promedio    37.58  38.09  43.76  47.16
...               ...    ...    ...    ...
nddi_min        37.58  38.09  43.76  47.16
enddi_promedio  37.58  38.09  43.76  47.16
enddi_std       37.58  38.09  43.76  47.16
enddi_max       37.58  38.09  43.76  47.16
enddi_min       37.58  38.09  43.76  47.16

[92 rows x 4 columns]

Diagnóstico: PRO
Registros: 47,804
Variables numéricas analizadas: 16

Porcentaje de valores faltantes por variable:

                faltantes_pct
ndvi_promedio           25.22
ndvi_std                25.22
ndvi_max                25.22
ndvi_min                25.22
evi_promedio            25.22
evi_std                 25.22
evi_max                 25.22
evi_min                 25.22
lai_promedio            25.22
lai_std                 25.22
lai_max                 25.22
lai_min                 25.22
msavi_promedio          25.22
msavi_std               25.22
msavi_max               25.22
msavi_min               25.22

Disponibilidad por sensor:

sensor          Planet
ndvi_promedio    74.78
ndvi_std         74.78
ndvi_max         74.78
ndvi_min         74.78
evi_promedio     74.78
evi_std          74.78
evi_max          74.78
evi_min          74.78
lai_promedio     74.78
lai_std          74.78
lai_max          74.78
lai_min          74.78
msavi_promedio   74.78
msavi_std        74.78
msavi_max        74.78
msavi_min        74.78

Disponibilidad por año:

ANIO             2025
ndvi_promedio   74.78
ndvi_std        74.78
ndvi_max        74.78
ndvi_min        74.78
evi_promedio    74.78
evi_std         74.78
evi_max         74.78
evi_min         74.78
lai_promedio    74.78
lai_std         74.78
lai_max         74.78
lai_min         74.78
msavi_promedio  74.78
msavi_std       74.78
msavi_max       74.78
msavi_min       74.78

In [5]:
# CELDA 4. Investigación de patrones de faltantes por sensor,
# periodo y parcela. No modifica los archivos oficiales.

import pandas as pd
import numpy as np

for nombre in ["BASICO", "PRO"]:
    df = datos_oficiales[nombre].copy()

    df["fecha_captura"] = pd.to_datetime(
        df["fecha_captura"],
        dayfirst=True,
        errors="coerce"
    )

    df["ANIO"] = df["fecha_captura"].dt.year
    df["MES"] = df["fecha_captura"].dt.month

    columnas_id = {
        "ID_POLIGONO", "fecha_captura", "sensor", "ANIO", "MES"
    }
    variables = [
        c for c in df.columns
        if c not in columnas_id
        and pd.api.types.is_numeric_dtype(df[c])
    ]

    print(f"\n{nombre}: REGISTROS POR SENSOR Y AÑO")
    display(
        df.groupby(["sensor", "ANIO"])
        .size()
        .rename("registros")
        .reset_index()
    )

    print(f"\n{nombre}: DISPONIBILIDAD MENSUAL")
    mensual = (
        df.groupby(["ANIO", "MES"])[variables]
        .apply(lambda bloque: bloque.notna().mean().mean() * 100)
        .rename("disponibilidad_media_pct")
        .reset_index()
    )
    display(mensual.round(2))

    print(f"\n{nombre}: COBERTURA POR PARCELA")
    cobertura = (
        df.groupby("ID_POLIGONO")[variables]
        .agg(lambda columna: columna.notna().mean() * 100)
        .mean(axis=1)
        .rename("disponibilidad_media_pct")
        .reset_index()
        .sort_values("disponibilidad_media_pct")
    )

    display(cobertura.head(10).round(2))
    display(cobertura.tail(10).round(2))

    print(f"\n{nombre}: OBSERVACIONES CON TODAS LAS VARIABLES VACÍAS")
    filas_vacias = df[variables].isna().all(axis=1)
    print(f"{filas_vacias.sum():,} de {len(df):,} registros")
    print(
        f"Porcentaje: {filas_vacias.mean() * 100:.2f}%"
    )

BASICO: REGISTROS POR SENSOR Y AÑO

       sensor  ANIO  registros
0     Landsat  2022      12806
1     Landsat  2023      13125
2     Landsat  2024      11759
3     Landsat  2025      10936
4  Sentinel-2  2022      13922
5  Sentinel-2  2023      13917
6  Sentinel-2  2024      14381
7  Sentinel-2  2025      16820

BASICO: DISPONIBILIDAD MENSUAL

    ANIO  MES  disponibilidad_media_pct
0   2022    1                     45.98
1   2022    2                     54.05
2   2022    3                     50.37
3   2022    4                     41.26
4   2022    5                     42.17
5   2022    6                     32.75
6   2022    7                     37.16
7   2022    8                     24.59
8   2022    9                     12.75
9   2022   10                     33.56
10  2022   11                     42.12
11  2022   12                     43.43
12  2023    1                     61.66
13  2023    2                     39.28
14  2023    3                     54.36
15  2023    4                     34.18
16  2023    5                     42.29
17  2023    6                     39.90
18  2023    7                     31.55
19  2023    8                     18.52
20  2023    9                     43.19
21  2023   10                     34.17
22  2023   11                     31.53
23  2023   12                     33.05
24  2024    1                     38.55
25  2024    2                     47.35
26  2024    3                     58.10
27  2024    4                     52.56
28  2024    5                     50.38
29  2024    6                     39.43
30  2024    7                     32.10
31  2024    8                     39.66
32  2024    9                     25.34
33  2024   10                     28.61
34  2024   11                     52.25
35  2024   12                     55.67
36  2025    1                     42.88
37  2025    2                     42.81
38  2025    3                     55.56
39  2025    4                     58.39
40  2025    5                     38.04
41  2025    6                     25.51
42  2025    7                     51.96
43  2025    8                     55.44
44  2025    9                     37.29
45  2025   10                     47.65
46  2025   11                     59.50
47  2025   12                     44.81

BASICO: COBERTURA POR PARCELA

    ID_POLIGONO  disponibilidad_media_pct
189     AGC_190                     31.77
12      AGC_013                     31.81
164     AGC_165                     32.12
87      AGC_088                     32.20
95      AGC_096                     32.58
30      AGC_031                     32.70
194     AGC_195                     32.74
107     AGC_108                     32.83
7       AGC_008                     32.88
61      AGC_062                     32.99

    ID_POLIGONO  disponibilidad_media_pct
182     AGC_183                     48.03
64      AGC_065                     48.17
22      AGC_023                     48.20
186     AGC_187                     48.21
116     AGC_117                     48.28
168     AGC_169                     48.31
26      AGC_027                     48.34
52      AGC_053                     48.37
169     AGC_170                     48.41
163     AGC_164                     48.60

BASICO: OBSERVACIONES CON TODAS LAS VARIABLES VACÍAS
3,056 de 107,666 registros
Porcentaje: 2.84%

PRO: REGISTROS POR SENSOR Y AÑO

   sensor  ANIO  registros
0  Planet  2025      47804

PRO: DISPONIBILIDAD MENSUAL

    ANIO  MES  disponibilidad_media_pct
0   2025    1                     72.55
1   2025    2                     83.29
2   2025    3                     95.86
3   2025    4                     94.38
4   2025    5                     72.04
5   2025    6                     57.85
6   2025    7                     63.38
7   2025    8                     74.95
8   2025    9                     56.74
9   2025   10                     66.12
10  2025   11                     87.40
11  2025   12                     71.42

PRO: COBERTURA POR PARCELA

    ID_POLIGONO  disponibilidad_media_pct
66      AGC_067                     65.20
88      AGC_089                     65.30
120     AGC_121                     66.21
77      AGC_078                     66.21
147     AGC_148                     66.90
6       AGC_007                     67.18
139     AGC_140                     67.42
80      AGC_081                     68.23
155     AGC_156                     68.23
33      AGC_034                     68.24

    ID_POLIGONO  disponibilidad_media_pct
119     AGC_120                     80.94
86      AGC_087                     81.57
26      AGC_027                     81.65
67      AGC_068                     81.89
163     AGC_164                     82.13
65      AGC_066                     82.20
70      AGC_071                     82.20
182     AGC_183                     82.50
169     AGC_170                     83.18
64      AGC_065                     83.48

PRO: OBSERVACIONES CON TODAS LAS VARIABLES VACÍAS
0 de 47,804 registros
Porcentaje: 0.00%

In [6]:
# CELDA 5. Coincidencia de faltantes y unicidad temporal

for nombre in ["BASICO", "PRO"]:
    df = datos_oficiales[nombre].copy()

    columnas_id = ["ID_POLIGONO", "fecha_captura", "sensor"]
    variables = [
        c for c in df.columns
        if c not in columnas_id + ["porcentaje_nubosidad"]
        and pd.api.types.is_numeric_dtype(df[c])
    ]

    faltantes = df[variables].isna()

    print(f"\n{nombre}")
    print("Filas:", len(df))
    print("Variables numéricas:", len(variables))

    # Número de variables vacías por fila
    conteo_vacias = faltantes.sum(axis=1)
    print("\nDistribución del número de variables vacías por fila:")
    display(
        conteo_vacias.value_counts()
        .sort_index()
        .rename_axis("variables_vacias")
        .to_frame("filas")
    )

    # Comprobar si los patrones de faltantes son idénticos
    patrones = faltantes.drop_duplicates()
    print("Patrones distintos de faltantes:", len(patrones))

    # Unicidad de las observaciones por parcela, fecha y sensor
    duplicados_clave = df.duplicated(
        subset=columnas_id,
        keep=False
    )

    print(
        "Filas implicadas en duplicados parcela-fecha-sensor:",
        int(duplicados_clave.sum())
    )

    # Comparación de cobertura por sensor
    if "sensor" in df.columns:
        print("\nCobertura de variables por sensor:")
        cobertura_sensor = (
            df.groupby("sensor")[variables]
            .apply(lambda grupo: grupo.notna().mean().mean() * 100)
        )
        display(cobertura_sensor.round(2).to_frame(
            "disponibilidad_media_pct"
        ))

BASICO
Filas: 107666
Variables numéricas: 92

Distribución del número de variables vacías por fila:

                  filas
variables_vacias
4                 44873
8                     4
88                31048
92                31741

Patrones distintos de faltantes: 4
Filas implicadas en duplicados parcela-fecha-sensor: 0

Cobertura de variables por sensor:

            disponibilidad_media_pct
sensor
Landsat                         2.78
Sentinel-2                     72.71

PRO
Filas: 47804
Variables numéricas: 16

Distribución del número de variables vacías por fila:

                  filas
variables_vacias
0                 35747
16                12057

Patrones distintos de faltantes: 2
Filas implicadas en duplicados parcela-fecha-sensor: 0

Cobertura de variables por sensor:

        disponibilidad_media_pct
sensor
Planet                     74.78

In [7]:
# CELDA 6. Auditoría específica por sensor y filas atípicas

basico = datos_oficiales["BASICO"].copy()

columnas_id = [
    "ID_POLIGONO",
    "fecha_captura",
    "sensor"
]

variables = [
    c for c in basico.columns
    if c not in columnas_id
    and pd.api.types.is_numeric_dtype(basico[c])
]

for sensor, grupo in basico.groupby("sensor"):
    print(f"\nSENSOR: {sensor}")
    print(f"Registros: {len(grupo):,}")

    auditoria = pd.DataFrame({
        "registros_con_dato": grupo[variables].notna().sum(),
        "disponibilidad_pct": grupo[variables].notna().mean() * 100,
        "valores_distintos": grupo[variables].nunique(dropna=True)
    }).sort_values(
        ["disponibilidad_pct", "registros_con_dato"],
        ascending=False
    )

    display(auditoria.round(2))

# Inspeccionar las cuatro filas con exactamente ocho variables vacías
conteo_vacias = basico[variables].isna().sum(axis=1)
atipicas = basico.loc[conteo_vacias == 8].copy()

print("\nFilas con exactamente ocho variables vacías:")
display(atipicas)

# Inspeccionar las columnas que sí contienen datos en esas filas
print("\nVariables disponibles en las filas atípicas:")
display(
    atipicas[variables]
    .notna()
    .sum()
    .loc[lambda s: s > 0]
    .rename("registros_con_dato")
    .to_frame()
)

SENSOR: Landsat
Registros: 48,626

,registros_con_dato,disponibilidad_pct,valores_distintos
porcentaje_nubosidad,45570,93.72,2251
vi6t_promedio,31048,63.85,229
vi6t_std,31048,63.85,65
vi6t_max,31048,63.85,301
vi6t_min,31048,63.85,237
...,...,...,...
nddi_min,0,0.00,0
enddi_promedio,0,0.00,0
enddi_std,0,0.00,0
enddi_max,0,0.00,0
enddi_min,0,0.00,0

SENSOR: Sentinel-2
Registros: 59,040

,registros_con_dato,disponibilidad_pct,valores_distintos
porcentaje_nubosidad,59040,100.00,6954
ndvi_promedio,44877,76.01,842
ndvi_std,44877,76.01,215
ndvi_max,44877,76.01,848
ndvi_min,44877,76.01,696
...,...,...,...
fapar_min,44873,76.00,648
vi6t_promedio,0,0.00,0
vi6t_std,0,0.00,0
vi6t_max,0,0.00,0
vi6t_min,0,0.00,0

Filas con exactamente ocho variables vacías:

,ID_POLIGONO,fecha_captura,sensor,ndvi_promedio,ndvi_std,ndvi_max,ndvi_min,evi_promedio,evi_std,evi_max,...,dswi5_min,nddi_promedio,nddi_std,nddi_max,nddi_min,enddi_promedio,enddi_std,enddi_max,enddi_min,porcentaje_nubosidad
15866,AGC_086,07/12/2022,Sentinel-2,0.169,0.013,0.282,0.149,0.126,0.011,0.205,...,0.689,0.102,0.015,0.126,0.050,0.172,0.014,0.192,0.110,0.0
73569,AGC_019,07/12/2022,Sentinel-2,0.170,0.048,0.453,0.116,0.114,0.040,0.378,...,0.653,0.119,0.021,0.179,0.065,0.153,0.022,0.237,0.104,0.0
102363,AGC_173,07/12/2022,Sentinel-2,0.267,0.096,0.628,0.085,0.177,0.101,0.567,...,0.602,0.111,0.035,0.169,-0.003,0.191,0.040,0.269,0.053,0.0
104330,AGC_103,07/12/2022,Sentinel-2,0.165,0.044,0.337,0.111,0.111,0.035,0.278,...,0.694,0.102,0.023,0.198,0.032,0.140,0.018,0.224,0.090,0.0

Variables disponibles en las filas atípicas:

                      registros_con_dato
ndvi_promedio                          4
ndvi_std                               4
ndvi_max                               4
ndvi_min                               4
evi_promedio                           4
...                                  ...
enddi_promedio                         4
enddi_std                              4
enddi_max                              4
enddi_min                              4
porcentaje_nubosidad                   4

[85 rows x 1 columns]

In [8]:
# CELDA 7. Cobertura anual por sensor y parcela

basico = datos_oficiales["BASICO"].copy()

basico["fecha_captura"] = pd.to_datetime(
    basico["fecha_captura"],
    dayfirst=True,
    errors="coerce"
)
basico["ANIO"] = basico["fecha_captura"].dt.year

variables_por_sensor = {
    "Landsat": [
        "vi6t_promedio",
        "vi6t_std",
        "vi6t_max",
        "vi6t_min",
    ],
    "Sentinel-2": [
        "ndvi_promedio",
        "evi_promedio",
        "lai_promedio",
        "fapar_promedio",
        "ndwi_promedio",
        "nddi_promedio",
    ],
}

for sensor, variables in variables_por_sensor.items():
    sub = basico.loc[basico["sensor"] == sensor].copy()

    # Usamos solo variables que realmente existen en la fuente.
    variables = [v for v in variables if v in sub.columns]

    # Una observación es válida si al menos una variable seleccionada
    # tiene un valor numérico.
    sub["observacion_valida"] = sub[variables].notna().any(axis=1)

    print(f"\n{sensor}: observaciones válidas por año")
    display(
        sub.groupby("ANIO")
        .agg(
            registros=("ID_POLIGONO", "size"),
            parcelas=("ID_POLIGONO", "nunique"),
            observaciones_validas=("observacion_valida", "sum"),
        )
        .assign(
            disponibilidad_pct=lambda x:
                100 * x["observaciones_validas"] / x["registros"]
        )
        .round(2)
    )

    print(f"\n{sensor}: cobertura por parcela y año")
    cobertura = (
        sub.groupby(["ID_POLIGONO", "ANIO"])
        .agg(
            registros=("ID_POLIGONO", "size"),
            observaciones_validas=("observacion_valida", "sum"),
        )
        .reset_index()
    )

    cobertura["disponibilidad_pct"] = (
        100 * cobertura["observaciones_validas"]
        / cobertura["registros"]
    )

    display(
        cobertura.sort_values(
            ["ANIO", "disponibilidad_pct"]
        ).head(15).round(2)
    )

Landsat: observaciones válidas por año

      registros  parcelas  observaciones_validas  disponibilidad_pct
ANIO
2022      12806       197                   7857               61.35
2023      13125       197                   8139               62.01
2024      11759       197                   7739               65.81
2025      10936       197                   7313               66.87

Landsat: cobertura por parcela y año

    ID_POLIGONO  ANIO  registros  observaciones_validas  disponibilidad_pct
604     AGC_152  2022        102                     34               33.33
332     AGC_084  2022        100                     34               34.00
120     AGC_031  2022        102                     36               35.29
600     AGC_151  2022        102                     36               35.29
544     AGC_137  2022        102                     37               36.27
552     AGC_139  2022        102                     37               36.27
776     AGC_195  2022        102                     37               36.27
244     AGC_062  2022        102                     38               37.25
380     AGC_096  2022        102                     38               37.25
456     AGC_115  2022        102                     38               37.25
288     AGC_073  2022        102                     39               38.24
324     AGC_082  2022        102                     39               38.24
740     AGC_186  2022        102                     39               38.24
28      AGC_008  2022        102                     40               39.22
48      AGC_013  2022        102                     40               39.22

Sentinel-2: observaciones válidas por año

      registros  parcelas  observaciones_validas  disponibilidad_pct
ANIO
2022      13922       197                  10045               72.15
2023      13917       197                  10301               74.02
2024      14381       197                  11440               79.55
2025      16820       197                  13091               77.83

Sentinel-2: cobertura por parcela y año

    ID_POLIGONO  ANIO  registros  observaciones_validas  disponibilidad_pct
352     AGC_089  2022         71                     44               61.97
272     AGC_069  2022         71                     45               63.38
420     AGC_106  2022         71                     46               64.79
436     AGC_110  2022         71                     46               64.79
616     AGC_155  2022         71                     46               64.79
508     AGC_128  2022         70                     46               65.71
732     AGC_184  2022         70                     46               65.71
16      AGC_005  2022         71                     47               66.20
44      AGC_012  2022         71                     47               66.20
64      AGC_017  2022         71                     47               66.20
84      AGC_022  2022         71                     47               66.20
108     AGC_028  2022         71                     47               66.20
224     AGC_057  2022         71                     47               66.20
264     AGC_067  2022         71                     47               66.20
364     AGC_092  2022         71                     47               66.20

In [10]:
# CELDA 8. Reconstrucción de las 51 variables satelitales Planet
# Fuente: archivos oficiales del reto.
# No utiliza tablas intermedias generadas en experimentos anteriores.

import pandas as pd
import numpy as np

from pathlib import Path

# 1. Definir las ventanas originales documentadas
VENTANAS = {
    "inicial": ("2025-04-01", "2025-05-31"),
    "intermedia": ("2025-06-01", "2025-07-31"),
    "tardia": ("2025-08-01", "2025-10-31"),
}

INDICES = ["ndvi", "evi", "lai", "msavi"]
ESTADISTICAS = ["promedio", "std", "max", "min"]

# 2. Leer nuevamente la fuente oficial PRO desde disco
ruta_pro = FUENTES_OFICIALES["PRO"]

pro_original = pd.read_csv(
    ruta_pro,
    dtype={"fecha_captura": "string"},
    low_memory=False
)

pro_original.columns = pro_original.columns.str.strip()

pro_original["ID_POLIGONO"] = (
    pro_original["ID_POLIGONO"].astype(str).str.strip()
)

pro_original["fecha_captura"] = pd.to_datetime(
    pro_original["fecha_captura"].str.strip(),
    format="%d/%m/%Y",
    errors="raise"
)

# Validaciones de la fuente
assert pro_original["ID_POLIGONO"].notna().all()
assert pro_original["fecha_captura"].notna().all()
assert not pro_original.duplicated(
    ["ID_POLIGONO", "fecha_captura", "sensor"]
).any()

pro_2025 = pro_original.loc[
    (pro_original["fecha_captura"].dt.year == 2025)
    & (pro_original["sensor"].eq("Planet"))
].copy()

assert pro_2025["ID_POLIGONO"].nunique() == 197

# 3. Verificar las 16 variables espectrales esperadas
VARIABLES_ESPECTRALES = [
    f"{indice}_{estadistica}"
    for indice in INDICES
    for estadistica in ESTADISTICAS
]

faltantes_columnas = sorted(
    set(VARIABLES_ESPECTRALES) - set(pro_2025.columns)
)

if faltantes_columnas:
    raise ValueError(
        f"Faltan variables espectrales oficiales: {faltantes_columnas}"
    )

# 4. Reconstruir cada ventana desde las observaciones originales
agregados = []

for nombre_ventana, (inicio, fin) in VENTANAS.items():
    inicio = pd.Timestamp(inicio)
    fin = pd.Timestamp(fin)

    bloque = pro_2025.loc[
        pro_2025["fecha_captura"].between(inicio, fin)
    ].copy()

    print(
        f"{nombre_ventana}: {len(bloque):,} observaciones, "
        f"{bloque['ID_POLIGONO'].nunique()} parcelas"
    )

    # Promedio temporal de las 16 estadísticas originales
    espectrales = (
        bloque.groupby("ID_POLIGONO")[VARIABLES_ESPECTRALES]
        .mean()
        .add_suffix(f"_{nombre_ventana}")
    )

    # Conteo de observaciones por parcela en la ventana
    cobertura = (
        bloque.groupby("ID_POLIGONO")
        .size()
        .rename(f"observaciones_{nombre_ventana}")
    )

    agregado = espectrales.join(cobertura, how="outer")
    agregados.append(agregado)

# 5. Unir las tres ventanas y conservar todos los IDs oficiales
planet_features_reconstruido = (
    pd.concat(agregados, axis=1)
    .reset_index()
)

planet_features_reconstruido["ID_POLIGONO"] = (
    planet_features_reconstruido["ID_POLIGONO"].astype(str).str.strip()
)

ids_oficiales = set(
    etiquetas["ID_POLIGONO"].astype(str).str.strip()
)

ids_reconstruidos = set(
    planet_features_reconstruido["ID_POLIGONO"]
)

if ids_reconstruidos != ids_oficiales:
    raise ValueError(
        "Los identificadores de Planet no coinciden con los oficiales. "
        f"Faltan: {len(ids_oficiales - ids_reconstruidos)}; "
        f"sobran: {len(ids_reconstruidos - ids_oficiales)}."
    )

if planet_features_reconstruido["ID_POLIGONO"].duplicated().any():
    raise ValueError("La tabla Planet reconstruida tiene IDs duplicados.")

# 6. Verificar la estructura esperada: 48 estadísticas + 3 conteos
features_planet = [
    c for c in planet_features_reconstruido.columns
    if c != "ID_POLIGONO"
]

assert len(features_planet) == 51, (
    f"Se esperaban 51 variables satelitales; "
    f"se obtuvieron {len(features_planet)}."
)

print("\nReconstrucción satelital terminada")
print("Dimensiones:", planet_features_reconstruido.shape)
print("Parcelas:", planet_features_reconstruido["ID_POLIGONO"].nunique())
print("Variables satelitales:", len(features_planet))

print("\nValores faltantes por variable:")
display(
    planet_features_reconstruido[features_planet]
    .isna()
    .sum()
    .loc[lambda s: s > 0]
    .to_frame("faltantes")
)

display(planet_features_reconstruido.head())

inicial: 9,196 observaciones, 197 parcelas
intermedia: 5,153 observaciones, 197 parcelas
tardia: 11,906 observaciones, 197 parcelas

Reconstrucción satelital terminada
Dimensiones: (197, 52)
Parcelas: 197
Variables satelitales: 51

Valores faltantes por variable:

Empty DataFrame
Columns: [faltantes]
Index: []

,ID_POLIGONO,ndvi_promedio_inicial,ndvi_std_inicial,ndvi_max_inicial,ndvi_min_inicial,evi_promedio_inicial,evi_std_inicial,evi_max_inicial,evi_min_inicial,lai_promedio_inicial,...,evi_min_tardia,lai_promedio_tardia,lai_std_tardia,lai_max_tardia,lai_min_tardia,msavi_promedio_tardia,msavi_std_tardia,msavi_max_tardia,msavi_min_tardia,observaciones_tardia
0,AGC_001,0.180081,0.027541,0.343703,0.108676,0.117757,0.017865,0.215108,0.067378,0.591243,...,0.265125,2.372000,0.264550,3.103675,1.595925,0.439350,0.066750,0.628750,0.261850,66
1,AGC_002,0.206000,0.025071,0.332595,0.142833,0.136524,0.018643,0.230500,0.090238,0.717929,...,0.249459,2.224757,0.231649,2.769649,1.601378,0.388838,0.053676,0.527838,0.245216,60
2,AGC_003,0.291121,0.037576,0.612667,0.165182,0.158364,0.023091,0.373303,0.091182,1.035242,...,0.193357,2.502893,0.283071,3.290250,1.380321,0.455036,0.093107,0.712107,0.187464,58
3,AGC_004,0.216475,0.031150,0.318175,0.042200,0.135375,0.019925,0.216450,0.035075,0.754850,...,0.029347,2.100286,0.587143,3.251531,0.068633,0.374755,0.121082,0.668918,0.027490,67
4,AGC_005,0.257450,0.033050,0.466425,0.175950,0.155650,0.018125,0.276125,0.107950,0.949700,...,0.293541,2.609784,0.277162,3.213405,1.781351,0.520973,0.095946,0.697270,0.280784,60

In [11]:
# CELDA 9. Integración de variables satelitales con etiquetas oficiales
# No utiliza matrices ni tablas intermedias de experimentos anteriores.

import pandas as pd
import numpy as np

etiquetas_oficiales = pd.read_csv(
    FUENTES_OFICIALES["ID_RENDIMIENTO"]
)

etiquetas_oficiales.columns = etiquetas_oficiales.columns.str.strip()
etiquetas_oficiales["ID_POLIGONO"] = (
    etiquetas_oficiales["ID_POLIGONO"].astype(str).str.strip()
)

# Validar la fuente oficial
assert len(etiquetas_oficiales) == 197
assert etiquetas_oficiales["ID_POLIGONO"].is_unique
assert etiquetas_oficiales["AREA_HA"].notna().all()
assert etiquetas_oficiales["CONJUNTO"].notna().all()

# Unir mediante el identificador, nunca por posición
matriz_base = etiquetas_oficiales[
    ["ID_POLIGONO", "AREA_HA", "RENDIMIENTO_T_HA", "CONJUNTO"]
].merge(
    planet_features_reconstruido,
    on="ID_POLIGONO",
    how="left",
    validate="one_to_one",
    indicator=True,
)

print("Coincidencia de IDs:")
print(matriz_base["_merge"].value_counts().to_dict())

assert matriz_base["_merge"].eq("both").all()
assert matriz_base["ID_POLIGONO"].is_unique
assert len(matriz_base) == 197

matriz_base = matriz_base.drop(columns="_merge")

columnas_satelitales = [
    c for c in planet_features_reconstruido.columns
    if c != "ID_POLIGONO"
]

print("\nDimensiones de la matriz base:", matriz_base.shape)
print("Variables satelitales:", len(columnas_satelitales))
print("Parcelas de entrenamiento:",
      matriz_base["RENDIMIENTO_T_HA"].notna().sum())
print("Parcelas de predicción:",
      matriz_base["RENDIMIENTO_T_HA"].isna().sum())
print("Faltantes en variables satelitales:",
      int(matriz_base[columnas_satelitales].isna().sum().sum()))
print("Faltantes en AREA_HA:",
      int(matriz_base["AREA_HA"].isna().sum()))

display(matriz_base.head())

Coincidencia de IDs:
{'both': 197, 'left_only': 0, 'right_only': 0}

Dimensiones de la matriz base: (197, 55)
Variables satelitales: 51
Parcelas de entrenamiento: 138
Parcelas de predicción: 59
Faltantes en variables satelitales: 0
Faltantes en AREA_HA: 0

,ID_POLIGONO,AREA_HA,RENDIMIENTO_T_HA,CONJUNTO,ndvi_promedio_inicial,ndvi_std_inicial,ndvi_max_inicial,ndvi_min_inicial,evi_promedio_inicial,evi_std_inicial,...,evi_min_tardia,lai_promedio_tardia,lai_std_tardia,lai_max_tardia,lai_min_tardia,msavi_promedio_tardia,msavi_std_tardia,msavi_max_tardia,msavi_min_tardia,observaciones_tardia
0,AGC_001,7.61,3.50,ENTRENAMIENTO,0.180081,0.027541,0.343703,0.108676,0.117757,0.017865,...,0.265125,2.372000,0.264550,3.103675,1.595925,0.439350,0.066750,0.628750,0.261850,66
1,AGC_002,2.31,4.63,ENTRENAMIENTO,0.206000,0.025071,0.332595,0.142833,0.136524,0.018643,...,0.249459,2.224757,0.231649,2.769649,1.601378,0.388838,0.053676,0.527838,0.245216,60
2,AGC_003,18.68,NaN,PREDICCION,0.291121,0.037576,0.612667,0.165182,0.158364,0.023091,...,0.193357,2.502893,0.283071,3.290250,1.380321,0.455036,0.093107,0.712107,0.187464,58
3,AGC_004,8.00,3.00,ENTRENAMIENTO,0.216475,0.031150,0.318175,0.042200,0.135375,0.019925,...,0.029347,2.100286,0.587143,3.251531,0.068633,0.374755,0.121082,0.668918,0.027490,67
4,AGC_005,2.27,5.16,ENTRENAMIENTO,0.257450,0.033050,0.466425,0.175950,0.155650,0.018125,...,0.293541,2.609784,0.277162,3.213405,1.781351,0.520973,0.095946,0.697270,0.280784,60

In [12]:
# CELDA 10. Inventario de posibles fuentes climáticas originales
# Solo inspección: no lee ni utiliza archivos intermedios.

from pathlib import Path
import pandas as pd

ROOT = Path.cwd().parent
RAW = ROOT / "data" / "raw"

EXTENSIONES = {
    ".tif", ".tiff", ".nc", ".grib", ".grb",
    ".csv", ".parquet", ".shp", ".gpkg",
    ".zip", ".hdf", ".h5", ".asc"
}

archivos = sorted(
    p for p in RAW.rglob("*")
    if p.is_file() and p.suffix.lower() in EXTENSIONES
)

inventario = []

for p in archivos:
    relativo = p.relative_to(ROOT).as_posix()
    nombre = p.name.lower()
    ruta_lower = relativo.lower()

    if any(k in nombre or k in ruta_lower for k in [
        "chirps", "precip", "rain", "era5", "chirts",
        "tmax", "tmin", "temperatura", "temperature",
        "climate", "clima"
    ]):
        categoria = "Clima"
    elif any(k in nombre or k in ruta_lower for k in [
        "agrocebada", "rendimiento", "area"
    ]):
        categoria = "Reto oficial / etiquetas"
    else:
        categoria = "Otra fuente raw"

    inventario.append({
        "archivo": relativo,
        "extension": p.suffix.lower(),
        "tamano_MB": round(p.stat().st_size / (1024 ** 2), 3),
        "categoria": categoria,
    })

inventario_raw = pd.DataFrame(inventario)

print("Raíz inspeccionada:", RAW)
print("Archivos tabulares/geoespaciales identificados:", len(archivos))

if inventario_raw.empty:
    print("No se encontraron archivos candidatos en data/raw.")
else:
    display(
        inventario_raw.sort_values(
            ["categoria", "archivo"]
        ).reset_index(drop=True)
    )

print("\nFuentes climáticas identificadas:")
if inventario_raw.empty:
    print("Ninguna.")
else:
    display(
        inventario_raw.loc[
            inventario_raw["categoria"].eq("Clima")
        ].reset_index(drop=True)
    )

Raíz inspeccionada: c:\Users\nonoe\OneDrive\Escritorio\Proyectos\AgroCebada-FIRA-2026\data\raw
Archivos tabulares/geoespaciales identificados: 150

,archivo,extension,tamano_MB,categoria
0,data/raw/climate/precipitation/2022/PREC_2022_...,.tif,0.011,Clima
1,data/raw/climate/precipitation/2022/PREC_2022_...,.tif,0.008,Clima
2,data/raw/climate/precipitation/2022/PREC_2022_...,.tif,0.009,Clima
3,data/raw/climate/precipitation/2022/PREC_2022_...,.tif,0.011,Clima
4,data/raw/climate/precipitation/2022/PREC_2022_...,.tif,0.011,Clima
...,...,...,...,...
145,data/raw/topography/Elevacion_INEGI_CEM4_120m.tif,.tif,4.281,Otra fuente raw
146,data/raw/topography/Pendiente_INEGI_CEM4_120m_...,.tif,12.784,Otra fuente raw
147,data/raw/tabular/Conjunto_datos_BASICO_AgroCeb...,.csv,32.109,Reto oficial / etiquetas
148,data/raw/tabular/Conjunto_datos_PRO_AgroCebada...,.csv,4.769,Reto oficial / etiquetas
149,data/raw/tabular/ID_area_rendimiento_70_30_Ret...,.csv,0.006,Reto oficial / etiquetas

Fuentes climáticas identificadas:

,archivo,extension,tamano_MB,categoria
0,data/raw/climate/precipitation/2022/PREC_2022_...,.tif,0.011,Clima
1,data/raw/climate/precipitation/2022/PREC_2022_...,.tif,0.008,Clima
2,data/raw/climate/precipitation/2022/PREC_2022_...,.tif,0.009,Clima
3,data/raw/climate/precipitation/2022/PREC_2022_...,.tif,0.011,Clima
4,data/raw/climate/precipitation/2022/PREC_2022_...,.tif,0.011,Clima
...,...,...,...,...
139,data/raw/climate/temperature/Tmin/2025/Tmin_20...,.tif,0.014,Clima
140,data/raw/climate/temperature/Tmin/2025/Tmin_20...,.tif,0.014,Clima
141,data/raw/climate/temperature/Tmin/2025/Tmin_20...,.tif,0.014,Clima
142,data/raw/climate/temperature/Tmin/2025/Tmin_20...,.tif,0.014,Clima
143,data/raw/climate/temperature/Tmin/2025/Tmin_20...,.tif,0.014,Clima

In [13]:

# CELDA 11. Inspección de fuentes climáticas originales

from pathlib import Path
import re
import pandas as pd

ROOT = Path.cwd().parent
RAW = ROOT / "data" / "raw"

carpetas_clima = [
    RAW / "climate" / "precipitation",
    RAW / "climate" / "temperature",
]

registros = []

for carpeta in carpetas_clima:
    if not carpeta.exists():
        print(f"ADVERTENCIA: no existe {carpeta.relative_to(ROOT)}")
        continue

    for archivo in sorted(carpeta.rglob("*")):
        if not archivo.is_file():
            continue

        nombre = archivo.name
        ruta_relativa = archivo.relative_to(ROOT).as_posix()

        # Extraer años y meses cuando estén presentes en el nombre
        anios = re.findall(r"20\d{2}", nombre)
        meses = re.findall(
            r"(?<!\d)(0?[1-9]|1[0-2])(?!\d)", nombre
        )

        registros.append({
            "archivo": ruta_relativa,
            "nombre": nombre,
            "carpeta": archivo.parent.relative_to(ROOT).as_posix(),
            "extension": archivo.suffix.lower(),
            "tamano_kb": round(archivo.stat().st_size / 1024, 2),
            "anios_en_nombre": ", ".join(dict.fromkeys(anios)),
            "posibles_meses_en_nombre": ", ".join(dict.fromkeys(meses)),
        })

inventario_climatico = pd.DataFrame(registros)

print("Total de archivos climáticos:", len(inventario_climatico))

if not inventario_climatico.empty:
    display(
        inventario_climatico
        .groupby(["carpeta", "extension"], dropna=False)
        .agg(
            cantidad=("archivo", "size"),
            tamano_total_kb=("tamano_kb", "sum"),
        )
        .reset_index()
    )

    print("\nPrimeros 30 archivos:")
    display(inventario_climatico.head(30))

    print("\nÚltimos 20 archivos:")
    display(inventario_climatico.tail(20))

Total de archivos climáticos: 144

,carpeta,extension,cantidad,tamano_total_kb
0,data/raw/climate/precipitation/2022,.tif,12,125.78
1,data/raw/climate/precipitation/2023,.tif,12,121.60
2,data/raw/climate/precipitation/2024,.tif,12,127.86
3,data/raw/climate/precipitation/2025,.tif,12,128.89
4,data/raw/climate/temperature/Tmax/2022,.tif,12,165.33
5,data/raw/climate/temperature/Tmax/2023,.tif,12,165.61
6,data/raw/climate/temperature/Tmax/2024,.tif,12,165.21
7,data/raw/climate/temperature/Tmax/2025,.tif,12,165.51
8,data/raw/climate/temperature/Tmin/2022,.tif,12,170.27
9,data/raw/climate/temperature/Tmin/2023,.tif,12,169.92
10,data/raw/climate/temperature/Tmin/2024,.tif,12,170.06
11,data/raw/climate/temperature/Tmin/2025,.tif,12,169.76

Primeros 30 archivos:

,archivo,nombre,carpeta,extension,tamano_kb,anios_en_nombre,posibles_meses_en_nombre
0,data/raw/climate/precipitation/2022/PREC_2022_...,PREC_2022_01.tif,data/raw/climate/precipitation/2022,.tif,11.01,2022,01
1,data/raw/climate/precipitation/2022/PREC_2022_...,PREC_2022_02.tif,data/raw/climate/precipitation/2022,.tif,7.98,2022,02
2,data/raw/climate/precipitation/2022/PREC_2022_...,PREC_2022_03.tif,data/raw/climate/precipitation/2022,.tif,9.40,2022,03
3,data/raw/climate/precipitation/2022/PREC_2022_...,PREC_2022_04.tif,data/raw/climate/precipitation/2022,.tif,10.91,2022,04
4,data/raw/climate/precipitation/2022/PREC_2022_...,PREC_2022_05.tif,data/raw/climate/precipitation/2022,.tif,10.77,2022,05
5,data/raw/climate/precipitation/2022/PREC_2022_...,PREC_2022_06.tif,data/raw/climate/precipitation/2022,.tif,11.00,2022,06
6,data/raw/climate/precipitation/2022/PREC_2022_...,PREC_2022_07.tif,data/raw/climate/precipitation/2022,.tif,11.11,2022,07
7,data/raw/climate/precipitation/2022/PREC_2022_...,PREC_2022_08.tif,data/raw/climate/precipitation/2022,.tif,10.85,2022,08
8,data/raw/climate/precipitation/2022/PREC_2022_...,PREC_2022_09.tif,data/raw/climate/precipitation/2022,.tif,11.00,2022,09
9,data/raw/climate/precipitation/2022/PREC_2022_...,PREC_2022_10.tif,data/raw/climate/precipitation/2022,.tif,10.95,2022,10
10,data/raw/climate/precipitation/2022/PREC_2022_...,PREC_2022_11.tif,data/raw/climate/precipitation/2022,.tif,11.01,2022,11
11,data/raw/climate/precipitation/2022/PREC_2022_...,PREC_2022_12.tif,data/raw/climate/precipitation/2022,.tif,9.79,2022,12
12,data/raw/climate/precipitation/2023/PREC_2023_...,PREC_2023_01.tif,data/raw/climate/precipitation/2023,.tif,6.88,2023,01
13,data/raw/climate/precipitation/2023/PREC_2023_...,PREC_2023_02.tif,data/raw/climate/precipitation/2023,.tif,6.09,2023,02
14,data/raw/climate/precipitation/2023/PREC_2023_...,PREC_2023_03.tif,data/raw/climate/precipitation/2023,.tif,9.93,2023,03
15,data/raw/climate/precipitation/2023/PREC_2023_...,PREC_2023_04.tif,data/raw/climate/precipitation/2023,.tif,10.96,2023,04
16,data/raw/climate/precipitation/2023/PREC_2023_...,PREC_2023_05.tif,data/raw/climate/precipitation/2023,.tif,10.74,2023,05
17,data/raw/climate/precipitation/2023/PREC_2023_...,PREC_2023_06.tif,data/raw/climate/precipitation/2023,.tif,10.92,2023,06
18,data/raw/climate/precipitation/2023/PREC_2023_...,PREC_2023_07.tif,data/raw/climate/precipitation/2023,.tif,10.98,2023,07
19,data/raw/climate/precipitation/2023/PREC_2023_...,PREC_2023_08.tif,data/raw/climate/precipitation/2023,.tif,10.86,2023,08
20,data/raw/climate/precipitation/2023/PREC_2023_...,PREC_2023_09.tif,data/raw/climate/precipitation/2023,.tif,10.99,2023,09
21,data/raw/climate/precipitation/2023/PREC_2023_...,PREC_2023_10.tif,data/raw/climate/precipitation/2023,.tif,11.02,2023,10
22,data/raw/climate/precipitation/2023/PREC_2023_...,PREC_2023_11.tif,data/raw/climate/precipitation/2023,.tif,11.20,2023,11
23,data/raw/climate/precipitation/2023/PREC_2023_...,PREC_2023_12.tif,data/raw/climate/precipitation/2023,.tif,11.03,2023,12
24,data/raw/climate/precipitation/2024/PREC_2024_...,PREC_2024_01.tif,data/raw/climate/precipitation/2024,.tif,10.57,2024,01
25,data/raw/climate/precipitation/2024/PREC_2024_...,PREC_2024_02.tif,data/raw/climate/precipitation/2024,.tif,10.47,2024,02
26,data/raw/climate/precipitation/2024/PREC_2024_...,PREC_2024_03.tif,data/raw/climate/precipitation/2024,.tif,8.55,2024,03
27,data/raw/climate/precipitation/2024/PREC_2024_...,PREC_2024_04.tif,data/raw/climate/precipitation/2024,.tif,11.04,2024,04
28,data/raw/climate/precipitation/2024/PREC_2024_...,PREC_2024_05.tif,data/raw/climate/precipitation/2024,.tif,10.81,2024,05
29,data/raw/climate/precipitation/2024/PREC_2024_...,PREC_2024_06.tif,data/raw/climate/precipitation/2024,.tif,10.76,2024,06

Últimos 20 archivos:

,archivo,nombre,carpeta,extension,tamano_kb,anios_en_nombre,posibles_meses_en_nombre
124,data/raw/climate/temperature/Tmin/2024/Tmin_20...,Tmin_2024_05.tif,data/raw/climate/temperature/Tmin/2024,.tif,13.91,2024,05
125,data/raw/climate/temperature/Tmin/2024/Tmin_20...,Tmin_2024_06.tif,data/raw/climate/temperature/Tmin/2024,.tif,14.20,2024,06
126,data/raw/climate/temperature/Tmin/2024/Tmin_20...,Tmin_2024_07.tif,data/raw/climate/temperature/Tmin/2024,.tif,14.26,2024,07
127,data/raw/climate/temperature/Tmin/2024/Tmin_20...,Tmin_2024_08.tif,data/raw/climate/temperature/Tmin/2024,.tif,14.32,2024,08
128,data/raw/climate/temperature/Tmin/2024/Tmin_20...,Tmin_2024_09.tif,data/raw/climate/temperature/Tmin/2024,.tif,14.26,2024,09
129,data/raw/climate/temperature/Tmin/2024/Tmin_20...,Tmin_2024_10.tif,data/raw/climate/temperature/Tmin/2024,.tif,14.29,2024,10
130,data/raw/climate/temperature/Tmin/2024/Tmin_20...,Tmin_2024_11.tif,data/raw/climate/temperature/Tmin/2024,.tif,14.46,2024,11
131,data/raw/climate/temperature/Tmin/2024/Tmin_20...,Tmin_2024_12.tif,data/raw/climate/temperature/Tmin/2024,.tif,14.45,2024,12
132,data/raw/climate/temperature/Tmin/2025/Tmin_20...,Tmin_2025_01.tif,data/raw/climate/temperature/Tmin/2025,.tif,14.34,2025,01
133,data/raw/climate/temperature/Tmin/2025/Tmin_20...,Tmin_2025_02.tif,data/raw/climate/temperature/Tmin/2025,.tif,13.87,2025,02
134,data/raw/climate/temperature/Tmin/2025/Tmin_20...,Tmin_2025_03.tif,data/raw/climate/temperature/Tmin/2025,.tif,13.70,2025,03
135,data/raw/climate/temperature/Tmin/2025/Tmin_20...,Tmin_2025_04.tif,data/raw/climate/temperature/Tmin/2025,.tif,13.86,2025,04
136,data/raw/climate/temperature/Tmin/2025/Tmin_20...,Tmin_2025_05.tif,data/raw/climate/temperature/Tmin/2025,.tif,13.92,2025,05
137,data/raw/climate/temperature/Tmin/2025/Tmin_20...,Tmin_2025_06.tif,data/raw/climate/temperature/Tmin/2025,.tif,14.16,2025,06
138,data/raw/climate/temperature/Tmin/2025/Tmin_20...,Tmin_2025_07.tif,data/raw/climate/temperature/Tmin/2025,.tif,14.29,2025,07
139,data/raw/climate/temperature/Tmin/2025/Tmin_20...,Tmin_2025_08.tif,data/raw/climate/temperature/Tmin/2025,.tif,14.30,2025,08
140,data/raw/climate/temperature/Tmin/2025/Tmin_20...,Tmin_2025_09.tif,data/raw/climate/temperature/Tmin/2025,.tif,14.26,2025,09
141,data/raw/climate/temperature/Tmin/2025/Tmin_20...,Tmin_2025_10.tif,data/raw/climate/temperature/Tmin/2025,.tif,14.31,2025,10
142,data/raw/climate/temperature/Tmin/2025/Tmin_20...,Tmin_2025_11.tif,data/raw/climate/temperature/Tmin/2025,.tif,14.53,2025,11
143,data/raw/climate/temperature/Tmin/2025/Tmin_20...,Tmin_2025_12.tif,data/raw/climate/temperature/Tmin/2025,.tif,14.22,2025,12

In [14]:

# CELDA 12. Auditoría de metadatos de los rásteres climáticos

from pathlib import Path
import pandas as pd
import rasterio
import importlib.util

ROOT = Path.cwd().parent
RAW = ROOT / "data" / "raw"

if importlib.util.find_spec("rasterio") is None:
    raise ImportError(
        "Falta rasterio. Instálalo en el entorno del notebook con: "
        "%pip install rasterio"
    )

carpetas = {
    "precipitacion": RAW / "climate" / "precipitation",
    "temperatura_maxima": RAW / "climate" / "temperature" / "Tmax",
    "temperatura_minima": RAW / "climate" / "temperature" / "Tmin",
}

metadatos = []

for variable, carpeta in carpetas.items():
    for archivo in sorted(carpeta.rglob("*.tif")):
        with rasterio.open(archivo) as src:
            banda = src.read(1, masked=True)
            valores = banda.compressed()

            metadatos.append({
                "variable": variable,
                "archivo": archivo.relative_to(ROOT).as_posix(),
                "ancho_px": src.width,
                "alto_px": src.height,
                "bandas": src.count,
                "crs": str(src.crs),
                "resolucion_x": src.res[0],
                "resolucion_y": src.res[1],
                "nodata": src.nodata,
                "pixeles_validos": int(valores.size),
                "minimo": float(valores.min()) if valores.size else None,
                "maximo": float(valores.max()) if valores.size else None,
                "media": float(valores.mean()) if valores.size else None,
            })

auditoria_raster = pd.DataFrame(metadatos)

print("Número de rásteres inspeccionados:", len(auditoria_raster))
print("\nResumen por variable:")

display(
    auditoria_raster.groupby("variable").agg(
        archivos=("archivo", "count"),
        sistemas_coordenadas=("crs", "nunique"),
        resoluciones=("resolucion_x", "nunique"),
        tamanos=("ancho_px", "nunique"),
        valores_minimos=("minimo", "min"),
        valores_maximos=("maximo", "max"),
    )
)

print("\nMuestra de archivos de cada variable:")

display(
    auditoria_raster.groupby("variable", group_keys=False)
    .head(2)
    .reset_index(drop=True)
)

Número de rásteres inspeccionados: 144

Resumen por variable:

,archivos,sistemas_coordenadas,resoluciones,tamanos,valores_minimos,valores_maximos
variable,,,,,,
precipitacion,48,1,1,1,0.000000,1487.481812
temperatura_maxima,48,1,1,1,17.059217,41.973110
temperatura_minima,48,1,1,1,4.773643,33.944027

Muestra de archivos de cada variable:

,variable,archivo,ancho_px,alto_px,bandas,crs,resolucion_x,resolucion_y,nodata,pixeles_validos,minimo,maximo,media
0,precipitacion,data/raw/climate/precipitation/2022/PREC_2022_...,65,72,1,EPSG:4326,0.05,0.05,-9999.0,2032,0.000000,131.202194,21.537550
1,precipitacion,data/raw/climate/precipitation/2022/PREC_2022_...,65,72,1,EPSG:4326,0.05,0.05,-9999.0,2032,0.000000,106.729340,12.222431
2,temperatura_maxima,data/raw/climate/temperature/Tmax/2022/Tmax_20...,65,72,1,EPSG:4326,0.05,0.05,-9999.0,4462,19.663115,29.675657,23.698545
3,temperatura_maxima,data/raw/climate/temperature/Tmax/2022/Tmax_20...,65,72,1,EPSG:4326,0.05,0.05,-9999.0,4462,20.132898,30.457623,24.396612
4,temperatura_minima,data/raw/climate/temperature/Tmin/2022/Tmin_20...,65,72,1,EPSG:4326,0.05,0.05,-9999.0,4462,5.647284,21.161032,11.354049
5,temperatura_minima,data/raw/climate/temperature/Tmin/2022/Tmin_20...,65,72,1,EPSG:4326,0.05,0.05,-9999.0,4462,6.137207,18.526161,11.311001

In [16]:
# ============================================================
# CELDA 13 — VALIDACIÓN DE RÁSTERES CLIMÁTICOS ORIGINALES
# Proyecto: Reto AgroCebada FIRA 2026
#
# Independencia:
# - Solo lee archivos originales de data/raw.
# - No consulta otros notebooks.
# - No carga matrices ni resultados intermedios.
# - No modifica ningún archivo.
# ============================================================

from pathlib import Path
import re
import pandas as pd

# ------------------------------------------------------------
# 1. LOCALIZAR LAS FUENTES ORIGINALES
# ------------------------------------------------------------

if "ROOT" not in globals():
    raise NameError(
        "No existe ROOT. Ejecuta primero la celda 1."
    )

RAW_DIR = Path(ROOT) / "data" / "raw"

if not RAW_DIR.is_dir():
    raise FileNotFoundError(
        f"No se encuentra el directorio de fuentes originales: {RAW_DIR}"
    )

# ------------------------------------------------------------
# 2. INVENTARIAR ARCHIVOS RÁSTER ORIGINALES
# ------------------------------------------------------------

archivos_tif = sorted(
    p for p in RAW_DIR.rglob("*")
    if p.is_file()
    and p.suffix.lower() in {".tif", ".tiff"}
)

if not archivos_tif:
    raise FileNotFoundError(
        f"No se encontraron GeoTIFF originales en {RAW_DIR}"
    )

print("Directorio de fuentes originales:", RAW_DIR)
print("GeoTIFF encontrados:", len(archivos_tif))

# ------------------------------------------------------------
# 3. IDENTIFICAR VARIABLES Y PERIODOS POR NOMBRE
# ------------------------------------------------------------

patron_fecha = re.compile(
    r"(?P<year>20\d{2})[_-](?P<month>0[1-9]|1[0-2])"
)

registros = []

for ruta in archivos_tif:
    nombre = ruta.stem.upper()

    if "PREC" in nombre or "PRECIP" in nombre:
        variable = "precipitacion"
    elif "TMAX" in nombre or "T_MAX" in nombre:
        variable = "temperatura_maxima"
    elif "TMIN" in nombre or "T_MIN" in nombre:
        variable = "temperatura_minima"
    else:
        variable = "sin_clasificar"

    coincidencia = patron_fecha.search(ruta.stem)

    if coincidencia:
        anio = int(coincidencia.group("year"))
        mes = int(coincidencia.group("month"))
    else:
        anio = None
        mes = None

    registros.append({
        "archivo": ruta.name,
        "ruta_relativa": str(ruta.relative_to(RAW_DIR)),
        "variable": variable,
        "anio": anio,
        "mes": mes,
        "bytes": ruta.stat().st_size,
    })

inventario_climatico = pd.DataFrame(registros)

# ------------------------------------------------------------
# 4. MOSTRAR COBERTURA TEMPORAL
# ------------------------------------------------------------

print("\n=== ARCHIVOS POR VARIABLE ===")
display(
    inventario_climatico
    .groupby("variable")
    .size()
    .rename("numero_archivos")
    .to_frame()
)

print("\n=== ARCHIVOS POR VARIABLE Y AÑO ===")
display(
    inventario_climatico
    .pivot_table(
        index="anio",
        columns="variable",
        values="archivo",
        aggfunc="count",
        fill_value=0
    )
    .sort_index()
)

print("\n=== PERIODOS IDENTIFICADOS ===")
display(
    inventario_climatico[
        ["archivo", "variable", "anio", "mes", "bytes"]
    ].sort_values(
        ["variable", "anio", "mes", "archivo"],
        na_position="last"
    ).reset_index(drop=True)
)

# ------------------------------------------------------------
# 5. AUDITORÍA DE INTEGRIDAD DEL INVENTARIO
# ------------------------------------------------------------

print("\n=== AUDITORÍA ===")
print("Archivos inventariados:", len(inventario_climatico))
print(
    "Archivos sin año o mes identificable:",
    int(inventario_climatico[["anio", "mes"]].isna().any(axis=1).sum())
)
print(
    "Archivos sin clasificar:",
    int((inventario_climatico["variable"] == "sin_clasificar").sum())
)
print(
    "Archivos vacíos:",
    int((inventario_climatico["bytes"] == 0).sum())
)

print(
    "\nNota: el nombre del archivo permite identificar candidatos, "
    "pero no confirma por sí solo las unidades, acumulaciones "
    "ni el periodo agronómico de cada variable."
)

Directorio de fuentes originales: c:\Users\nonoe\OneDrive\Escritorio\Proyectos\AgroCebada-FIRA-2026\data\raw
GeoTIFF encontrados: 146

=== ARCHIVOS POR VARIABLE ===

                    numero_archivos
variable
precipitacion                    48
sin_clasificar                    2
temperatura_maxima               48
temperatura_minima               48

=== ARCHIVOS POR VARIABLE Y AÑO ===

variable  precipitacion  temperatura_maxima  temperatura_minima
anio
2022.0               12                  12                  12
2023.0               12                  12                  12
2024.0               12                  12                  12
2025.0               12                  12                  12

=== PERIODOS IDENTIFICADOS ===

              archivo            variable    anio   mes  bytes
0    PREC_2022_01.tif       precipitacion  2022.0   1.0  11276
1    PREC_2022_02.tif       precipitacion  2022.0   2.0   8174
2    PREC_2022_03.tif       precipitacion  2022.0   3.0   9630
3    PREC_2022_04.tif       precipitacion  2022.0   4.0  11174
4    PREC_2022_05.tif       precipitacion  2022.0   5.0  11032
..                ...                 ...     ...   ...    ...
141  Tmin_2025_08.tif  temperatura_minima  2025.0   8.0  14644
142  Tmin_2025_09.tif  temperatura_minima  2025.0   9.0  14606
143  Tmin_2025_10.tif  temperatura_minima  2025.0  10.0  14650
144  Tmin_2025_11.tif  temperatura_minima  2025.0  11.0  14878
145  Tmin_2025_12.tif  temperatura_minima  2025.0  12.0  14566

[146 rows x 5 columns]

=== AUDITORÍA ===
Archivos inventariados: 146
Archivos sin año o mes identificable: 2
Archivos sin clasificar: 2
Archivos vacíos: 0

Nota: el nombre del archivo permite identificar candidatos, pero no confirma por sí solo las unidades, acumulaciones ni el periodo agronómico de cada variable.

In [17]:
# CELDA 14 — AUDITORÍA DE ESQUEMAS DE LAS FUENTES OFICIALES


import pandas as pd

for nombre, df in datos_oficiales.items():
    print(f"\n{'=' * 70}")
    print(f"FUENTE: {nombre}")
    print("Dimensiones:", df.shape)
    print("Columnas:")
    for columna in df.columns:
        print(f"  - {columna}")

======================================================================
FUENTE: BASICO
Dimensiones: (107666, 96)
Columnas:
  - ID_POLIGONO
  - fecha_captura
  - sensor
  - ndvi_promedio
  - ndvi_std
  - ndvi_max
  - ndvi_min
  - evi_promedio
  - evi_std
  - evi_max
  - evi_min
  - crc_promedio
  - crc_std
  - crc_max
  - crc_min
  - mcrc_promedio
  - mcrc_std
  - mcrc_max
  - mcrc_min
  - ndsvi_promedio
  - ndsvi_std
  - ndsvi_max
  - ndsvi_min
  - srndi_promedio
  - srndi_std
  - srndi_max
  - srndi_min
  - mra_promedio
  - mra_std
  - mra_max
  - mra_min
  - lai_promedio
  - lai_std
  - lai_max
  - lai_min
  - fapar_promedio
  - fapar_std
  - fapar_max
  - fapar_min
  - savi_promedio
  - savi_std
  - savi_max
  - savi_min
  - vi6t_promedio
  - vi6t_std
  - vi6t_max
  - vi6t_min
  - ndti_promedio
  - ndti_std
  - ndti_max
  - ndti_min
  - sti_promedio
  - sti_std
  - sti_max
  - sti_min
  - ndwi_promedio
  - ndwi_std
  - ndwi_max
  - ndwi_min
  - endwi_promedio
  - endwi_std
  - endwi_max
  - endwi_min
  - msi_promedio
  - msi_std
  - msi_max
  - msi_min
  - emsi_promedio
  - emsi_std
  - emsi_max
  - emsi_min
  - dswi2_promedio
  - dswi2_std
  - dswi2_max
  - dswi2_min
  - dswi3_promedio
  - dswi3_std
  - dswi3_max
  - dswi3_min
  - dswi4_promedio
  - dswi4_std
  - dswi4_max
  - dswi4_min
  - dswi5_promedio
  - dswi5_std
  - dswi5_max
  - dswi5_min
  - nddi_promedio
  - nddi_std
  - nddi_max
  - nddi_min
  - enddi_promedio
  - enddi_std
  - enddi_max
  - enddi_min
  - porcentaje_nubosidad

======================================================================
FUENTE: PRO
Dimensiones: (47804, 20)
Columnas:
  - ID_POLIGONO
  - fecha_captura
  - sensor
  - ndvi_promedio
  - ndvi_std
  - ndvi_max
  - ndvi_min
  - evi_promedio
  - evi_std
  - evi_max
  - evi_min
  - lai_promedio
  - lai_std
  - lai_max
  - lai_min
  - msavi_promedio
  - msavi_std
  - msavi_max
  - msavi_min
  - porcentaje_nubosidad

======================================================================
FUENTE: ID_RENDIMIENTO
Dimensiones: (197, 5)
Columnas:
  - ID_POLIGONO
  - AREA_HA
  - RENDIMIENTO_T_HA
  - CONJUNTO
  - Unnamed: 4

In [18]:
# CELDA 15 — COBERTURA TEMPORAL DE LAS FUENTES SATELITALES


import pandas as pd

for nombre in ["BASICO", "PRO"]:
    df = datos_oficiales[nombre].copy()

    df["fecha_captura"] = pd.to_datetime(
        df["fecha_captura"],
        errors="coerce"
    )

    print(f"\n{'=' * 65}")
    print(f"FUENTE: {nombre}")
    print("Registros:", len(df))
    print("Parcelas únicas:", df["ID_POLIGONO"].nunique())
    print(
        "Fechas no interpretables:",
        int(df["fecha_captura"].isna().sum())
    )
    print(
        "Primera fecha:",
        df["fecha_captura"].min()
    )
    print(
        "Última fecha:",
        df["fecha_captura"].max()
    )

    print("\nRegistros por año:")
    print(
        df.groupby(df["fecha_captura"].dt.year)
        .size()
        .rename("registros")
        .to_string()
    )

    print("\nSensores:")
    print(
        df["sensor"]
        .fillna("SIN DATO")
        .value_counts(dropna=False)
        .to_string()
    )

    print("\nFechas distintas:", df["fecha_captura"].nunique())

C:\Users\nonoe\AppData\Local\Temp\ipykernel_18900\1444058592.py:9: UserWarning: Parsing dates in %d/%m/%Y format when dayfirst=False (the default) was specified. Pass `dayfirst=True` or specify a format to silence this warning.
  df["fecha_captura"] = pd.to_datetime(

=================================================================
FUENTE: BASICO
Registros: 107666
Parcelas únicas: 197
Fechas no interpretables: 0
Primera fecha: 2022-01-01 00:00:00
Última fecha: 2025-12-31 00:00:00

Registros por año:
fecha_captura
2022    26728
2023    27042
2024    26140
2025    27756

Sensores:
sensor
Sentinel-2    59040
Landsat       48626

Fechas distintas: 608

=================================================================
FUENTE: PRO
Registros: 47804
Parcelas únicas: 197
Fechas no interpretables: 28304
Primera fecha: 2025-01-01 00:00:00
Última fecha: 2025-12-12 00:00:00

Registros por año:
fecha_captura
2025.0    19500

Sensores:
sensor
Planet    47804

Fechas distintas: 126

In [19]:
# CELDA 16 — COBERTURA MENSUAL POR SENSOR
# Fuentes: CSV oficiales BASICO y PRO exclusivamente.

import pandas as pd

for nombre in ["BASICO", "PRO"]:
    df = datos_oficiales[nombre].copy()

    # Las fechas oficiales pueden venir como DD/MM/YYYY.
    df["fecha_captura"] = pd.to_datetime(
        df["fecha_captura"],
        format="mixed",
        dayfirst=True,
        errors="coerce"
    )

    print(f"\n{'=' * 65}")
    print(f"FUENTE: {nombre}")

    # Número de registros por año y mes.
    cobertura = (
        df.dropna(subset=["fecha_captura"])
        .assign(
            anio=lambda x: x["fecha_captura"].dt.year,
            mes=lambda x: x["fecha_captura"].dt.month
        )
        .groupby(["sensor", "anio", "mes"])
        .agg(
            registros=("ID_POLIGONO", "size"),
            parcelas=("ID_POLIGONO", "nunique"),
            fechas=("fecha_captura", "nunique")
        )
        .reset_index()
        .sort_values(["sensor", "anio", "mes"])
    )

    display(cobertura)

    print(
        "\nRegistros con fecha inválida:",
        int(df["fecha_captura"].isna().sum())
    )

=================================================================
FUENTE: BASICO

        sensor  anio  mes  registros  parcelas  fechas
0      Landsat  2022    1        909       197       8
1      Landsat  2022    2        701       197       6
2      Landsat  2022    3        736       197       7
3      Landsat  2022    4       1062       197       8
4      Landsat  2022    5       1271       197       9
..         ...   ...  ...        ...       ...     ...
91  Sentinel-2  2025    8       1379       197       7
92  Sentinel-2  2025    9       1318       197       7
93  Sentinel-2  2025   10       1379       197       7
94  Sentinel-2  2025   11       1515       197       8
95  Sentinel-2  2025   12       1576       197       8

[96 rows x 6 columns]

Registros con fecha inválida: 0

=================================================================
FUENTE: PRO

    sensor  anio  mes  registros  parcelas  fechas
0   Planet  2025    1       4316       197      28
1   Planet  2025    2       4135       197      24
2   Planet  2025    3       5166       197      31
3   Planet  2025    4       4760       197      29
4   Planet  2025    5       4436       197      25
5   Planet  2025    6       2213       197      18
6   Planet  2025    7       2940       197      22
7   Planet  2025    8       4381       197      27
8   Planet  2025    9       3964       197      29
9   Planet  2025   10       3561       197      26
10  Planet  2025   11       3407       197      25
11  Planet  2025   12       4525       197      27

Registros con fecha inválida: 0

In [20]:
# CELDA 17 — INTEGRIDAD TEMPORAL POR PARCELA
# Solo fuentes CSV oficiales.

import pandas as pd

for nombre in ["BASICO", "PRO"]:
    df = datos_oficiales[nombre].copy()

    df["fecha_captura"] = pd.to_datetime(
        df["fecha_captura"],
        format="mixed",
        dayfirst=True,
        errors="coerce"
    )

    resumen = (
        df.groupby("ID_POLIGONO")
        .agg(
            registros=("fecha_captura", "size"),
            fechas_distintas=("fecha_captura", "nunique"),
            fecha_inicial=("fecha_captura", "min"),
            fecha_final=("fecha_captura", "max"),
            sensores=("sensor", "nunique")
        )
        .reset_index()
    )

    print(f"\n{'=' * 65}")
    print(f"FUENTE: {nombre}")
    print("Parcelas:", len(resumen))
    print("\nResumen estadístico:")
    display(
        resumen[
            ["registros", "fechas_distintas", "sensores"]
        ].describe().round(2)
    )

    print("\nParcelas con menos fechas distintas:")
    display(
        resumen.sort_values(
            ["fechas_distintas", "registros"]
        ).head(10)
    )

    print("\nParcelas con más fechas distintas:")
    display(
        resumen.sort_values(
            ["fechas_distintas", "registros"],
            ascending=False
        ).head(10)
    )

=================================================================
FUENTE: BASICO
Parcelas: 197

Resumen estadístico:

       registros  fechas_distintas  sensores
count     197.00            197.00     197.0
mean      546.53            491.14       2.0
std        65.28             53.04       0.0
min       494.00            449.00       2.0
25%       504.00            456.00       2.0
50%       511.00            462.00       2.0
75%       573.00            517.00       2.0
max       692.00            607.00       2.0

Parcelas con menos fechas distintas:

,ID_POLIGONO,registros,fechas_distintas,fecha_inicial,fecha_final,sensores
8,AGC_009,494,449,2022-01-01,2025-12-31,2
118,AGC_119,496,450,2022-01-01,2025-12-31,2
179,AGC_180,499,453,2022-01-01,2025-12-31,2
21,AGC_022,500,453,2022-01-01,2025-12-31,2
196,AGC_197,501,453,2022-01-01,2025-12-31,2
100,AGC_101,502,454,2022-01-01,2025-12-31,2
80,AGC_081,503,454,2022-01-01,2025-12-31,2
88,AGC_089,503,454,2022-01-01,2025-12-31,2
121,AGC_122,500,455,2022-01-01,2025-12-31,2
168,AGC_169,500,455,2022-01-01,2025-12-31,2

Parcelas con más fechas distintas:

,ID_POLIGONO,registros,fechas_distintas,fecha_inicial,fecha_final,sensores
7,AGC_008,692,607,2022-01-01,2025-12-31,2
12,AGC_013,692,607,2022-01-01,2025-12-31,2
30,AGC_031,692,607,2022-01-01,2025-12-31,2
61,AGC_062,692,607,2022-01-01,2025-12-31,2
72,AGC_073,692,607,2022-01-01,2025-12-31,2
87,AGC_088,692,607,2022-01-01,2025-12-31,2
95,AGC_096,692,607,2022-01-01,2025-12-31,2
114,AGC_115,692,607,2022-01-01,2025-12-31,2
138,AGC_139,692,607,2022-01-01,2025-12-31,2
185,AGC_186,692,607,2022-01-01,2025-12-31,2

=================================================================
FUENTE: PRO
Parcelas: 197

Resumen estadístico:

       registros  fechas_distintas  sensores
count     197.00            197.00     197.0
mean      242.66            242.66       1.0
std         4.42              4.42       0.0
min       233.00            233.00       1.0
25%       240.00            240.00       1.0
50%       243.00            243.00       1.0
75%       246.00            246.00       1.0
max       251.00            251.00       1.0

Parcelas con menos fechas distintas:

,ID_POLIGONO,registros,fechas_distintas,fecha_inicial,fecha_final,sensores
73,AGC_074,233,233,2025-01-01,2025-12-30,1
122,AGC_123,233,233,2025-01-01,2025-12-30,1
29,AGC_030,234,234,2025-01-01,2025-12-30,1
77,AGC_078,234,234,2025-01-01,2025-12-30,1
79,AGC_080,234,234,2025-01-01,2025-12-30,1
120,AGC_121,234,234,2025-01-01,2025-12-30,1
139,AGC_140,234,234,2025-01-01,2025-12-30,1
143,AGC_144,234,234,2025-01-01,2025-12-30,1
38,AGC_039,235,235,2025-01-01,2025-12-30,1
49,AGC_050,235,235,2025-01-01,2025-12-30,1

Parcelas con más fechas distintas:

,ID_POLIGONO,registros,fechas_distintas,fecha_inicial,fecha_final,sensores
81,AGC_082,251,251,2025-01-01,2025-12-29,1
83,AGC_084,251,251,2025-01-01,2025-12-29,1
145,AGC_146,251,251,2025-01-01,2025-12-29,1
150,AGC_151,251,251,2025-01-01,2025-12-29,1
106,AGC_107,250,250,2025-01-01,2025-12-29,1
127,AGC_128,250,250,2025-01-01,2025-12-29,1
133,AGC_134,250,250,2025-01-01,2025-12-30,1
136,AGC_137,250,250,2025-01-01,2025-12-29,1
151,AGC_152,250,250,2025-01-01,2025-12-29,1
188,AGC_189,250,250,2025-01-01,2025-12-29,1

In [21]:
# CELDA 18 — IDENTIFICAR LOS GEOTIFF SIN CLASIFICAR

from pathlib import Path

raw_dir = Path(ROOT) / "data" / "raw"

archivos_tif = sorted(
    p for p in raw_dir.rglob("*")
    if p.is_file() and p.suffix.lower() in {".tif", ".tiff"}
)

print("GeoTIFF encontrados:", len(archivos_tif))
print("\nArchivos que no parecen pertenecer a las series climáticas mensuales:")

for p in archivos_tif:
    nombre = p.name.lower()

    es_climatico_mensual = (
        nombre.startswith("prec_")
        or nombre.startswith("precip_")
        or nombre.startswith("tmax_")
        or nombre.startswith("tmin_")
    )

    if not es_climatico_mensual:
        print(f"{p.name} | {p.stat().st_size:,} bytes")

GeoTIFF encontrados: 146

Archivos que no parecen pertenecer a las series climáticas mensuales:
Elevacion_INEGI_CEM4_120m.tif | 4,488,499 bytes
Pendiente_INEGI_CEM4_120m_grados.tif | 13,405,501 bytes

In [22]:
# CELDA 19 — AUDITORÍA DEL SHAPEFILE ORIGINAL DE PARCELAS

from pathlib import Path
import geopandas as gpd

shp_path = Path(ROOT) / "data" / "raw" / "Parcelas_Reto_AGC_CONJUNTO.shp"

if not shp_path.exists():
    candidatos = list(
        (Path(ROOT) / "data" / "raw").rglob(
            "Parcelas_Reto_AGC_CONJUNTO.shp"
        )
    )
    if len(candidatos) != 1:
        raise FileNotFoundError(
            "No se encontró una única ruta para el shapefile original. "
            f"Candidatos: {candidatos}"
        )
    shp_path = candidatos[0]

parcelas_geo = gpd.read_file(shp_path)

print("Archivo:", shp_path.name)
print("Dimensiones:", parcelas_geo.shape)
print("CRS:", parcelas_geo.crs)
print("Tipo de geometría:")
print(parcelas_geo.geometry.geom_type.value_counts(dropna=False))

print("\nColumnas:")
print(parcelas_geo.columns.tolist())

print("\nPrimeros registros:")
display(parcelas_geo.head())

print("\nIntegridad geométrica:")
print("Geometrías nulas:", int(parcelas_geo.geometry.isna().sum()))
print("Geometrías vacías:", int(parcelas_geo.geometry.is_empty.sum()))
print("Geometrías inválidas:", int((~parcelas_geo.geometry.is_valid).sum()))

col_id = next(
    (c for c in ["ID_POLIGONO", "ID_POLIGON"] if c in parcelas_geo.columns),
    None
)

if col_id is None:
    print("\nNo se encontró la columna de identificador esperada.")
else:
    print("\nColumna de ID:", col_id)
    print("IDs nulos:", int(parcelas_geo[col_id].isna().sum()))
    print("IDs únicos:", parcelas_geo[col_id].nunique())
    print("IDs duplicados:", int(parcelas_geo[col_id].duplicated().sum()))

Archivo: Parcelas_Reto_AGC_CONJUNTO.shp
Dimensiones: (197, 7)
CRS: EPSG:4326
Tipo de geometría:
Polygon    197
Name: count, dtype: int64

Columnas:
['Cultivo', 'ID_POLIGON', 'área_ha', 'Municipio', 'Estado', 'CONJUNTO', 'geometry']

Primeros registros:

,Cultivo,ID_POLIGON,área_ha,Municipio,Estado,CONJUNTO,geometry
0,Cebada,AGC_196,8.57,Emiliano Zapata,Hidalgo,ENTRENAMIENTO,"POLYGON Z ((-98.57739 19.65802 0, -98.57751 19..."
1,Cebada,AGC_044,0.68,Emiliano Zapata,Hidalgo,ENTRENAMIENTO,"POLYGON Z ((-98.58655 19.62943 0, -98.5862 19...."
2,Cebada,AGC_020,8.34,Emiliano Zapata,Hidalgo,ENTRENAMIENTO,"POLYGON Z ((-98.58494 19.6278 0, -98.58656 19...."
3,CEBADA,AGC_174,6.89,Cuautepec de Hinojosa,Hidalgo,PREDICCION,"POLYGON Z ((-98.30604 19.9 0, -98.30486 19.899..."
4,CEBADA,AGC_083,2.87,Cuautepec de Hinojosa,Hidalgo,ENTRENAMIENTO,"POLYGON Z ((-98.29383 19.8882 0, -98.29378 19...."

Integridad geométrica:
Geometrías nulas: 0
Geometrías vacías: 0
Geometrías inválidas: 0

Columna de ID: ID_POLIGON
IDs nulos: 0
IDs únicos: 197
IDs duplicados: 0

In [23]:
# CELDA 20 — COBERTURA ESPACIAL DE PARCELAS Y RÁSTERES CLIMÁTICOS

from pathlib import Path
import rasterio
import geopandas as gpd

raw_dir = Path(ROOT) / "data" / "raw"

# Usamos exclusivamente el shapefile original y un ráster climático original.
rasteres_clima = sorted(
    p for p in raw_dir.rglob("*")
    if p.is_file()
    and p.suffix.lower() in {".tif", ".tiff"}
    and p.name.lower().startswith(("prec_", "precip_", "tmax_", "tmin_"))
)

if not rasteres_clima:
    raise FileNotFoundError("No se encontraron rásteres climáticos originales.")

raster_ref = rasteres_clima[0]

with rasterio.open(raster_ref) as src:
    raster_crs = src.crs
    raster_bounds = src.bounds
    raster_res = src.res
    raster_shape = (src.height, src.width)
    raster_nodata = src.nodata

print("Ráster de referencia:", raster_ref.name)
print("CRS:", raster_crs)
print("Extensión:", raster_bounds)
print("Resolución:", raster_res)
print("Dimensiones:", raster_shape)
print("NoData:", raster_nodata)

parcelas_clima = parcelas_geo.to_crs(raster_crs)

print("\nCobertura de parcelas:")
print("Parcelas:", len(parcelas_clima))
print("Dentro de la extensión del ráster:",
      int(parcelas_clima.geometry.apply(
          lambda g: (
              g.bounds[0] >= raster_bounds.left
              and g.bounds[1] >= raster_bounds.bottom
              and g.bounds[2] <= raster_bounds.right
              and g.bounds[3] <= raster_bounds.top
          )
      ).sum()))
print("Fuera o parcialmente fuera de la extensión:",
      int((~parcelas_clima.geometry.apply(
          lambda g: (
              g.bounds[0] >= raster_bounds.left
              and g.bounds[1] >= raster_bounds.bottom
              and g.bounds[2] <= raster_bounds.right
              and g.bounds[3] <= raster_bounds.top
          )
      )).sum()))

print("\nExtensión conjunta de parcelas:")
print(parcelas_clima.total_bounds)

Ráster de referencia: PREC_2022_01.tif
CRS: EPSG:4326
Extensión: BoundingBox(left=-99.94999880716205, bottom=17.79999952018261, right=-96.69999875873327, top=21.39999957382679)
Resolución: (0.05000000074505806, 0.05000000074505806)
Dimensiones: (72, 65)
NoData: -9999.0

Cobertura de parcelas:
Parcelas: 197
Dentro de la extensión del ráster: 197
Fuera o parcialmente fuera de la extensión: 0

Extensión conjunta de parcelas:
[-98.612993    19.523825   -98.19669951  19.9843652 ]

In [24]:

# CELDA 21 — INVENTARIO DE DATOS ORIGINALES

from pathlib import Path
from collections import Counter

raw_dir = Path(ROOT) / "data" / "raw"

if not raw_dir.exists():
    raise FileNotFoundError(f"No existe el directorio de datos originales: {raw_dir}")

archivos = sorted(p for p in raw_dir.rglob("*") if p.is_file())

print(f"Directorio analizado: {raw_dir.resolve()}")
print(f"Total de archivos: {len(archivos)}")

print("\n--- ARCHIVOS POR EXTENSIÓN ---")
conteo = Counter(
    p.suffix.lower() if p.suffix else "[sin extensión]"
    for p in archivos
)
for extension, cantidad in conteo.most_common():
    print(f"{extension:15} {cantidad}")

print("\n--- ARCHIVOS VECTORIALES Y TABULARES ---")
extensiones_interes = {
    ".shp", ".gpkg", ".geojson", ".gml",
    ".csv", ".xlsx", ".xls", ".dbf", ".prj"
}
for p in archivos:
    if p.suffix.lower() in extensiones_interes:
        print(p.relative_to(raw_dir))

print("\n--- RÁSTERES ORIGINALES ---")
rasteres = [
    p for p in archivos
    if p.suffix.lower() in {".tif", ".tiff", ".img", ".vrt"}
]
print(f"Total de rásteres: {len(rasteres)}")

conteo_raster = Counter(p.name.split("_")[0].upper() for p in rasteres)
for prefijo, cantidad in conteo_raster.most_common():
    print(f"{prefijo:15} {cantidad}")

print("\n--- MUESTRA DE RÁSTERES ---")
for p in rasteres[:30]:
    print(p.relative_to(raw_dir))

if len(rasteres) > 30:
    print(f"... y {len(rasteres) - 30} rásteres adicionales.")

Directorio analizado: C:\Users\nonoe\OneDrive\Escritorio\Proyectos\AgroCebada-FIRA-2026\data\raw
Total de archivos: 154

--- ARCHIVOS POR EXTENSIÓN ---
.tif            146
.csv            3
.cpg            1
.dbf            1
.prj            1
.shp            1
.shx            1

--- ARCHIVOS VECTORIALES Y TABULARES ---
parcels\Parcelas_Reto_AGC_CONJUNTO.dbf
parcels\Parcelas_Reto_AGC_CONJUNTO.prj
parcels\Parcelas_Reto_AGC_CONJUNTO.shp
tabular\Conjunto_datos_BASICO_AgroCebada2026.csv
tabular\Conjunto_datos_PRO_AgroCebada.csv
tabular\ID_area_rendimiento_70_30_Reto_AgroCebada.csv

--- RÁSTERES ORIGINALES ---
Total de rásteres: 146
PREC            48
TMAX            48
TMIN            48
ELEVACION       1
PENDIENTE       1

--- MUESTRA DE RÁSTERES ---
climate\precipitation\2022\PREC_2022_01.tif
climate\precipitation\2022\PREC_2022_02.tif
climate\precipitation\2022\PREC_2022_03.tif
climate\precipitation\2022\PREC_2022_04.tif
climate\precipitation\2022\PREC_2022_05.tif
climate\precipitation\2022\PREC_2022_06.tif
climate\precipitation\2022\PREC_2022_07.tif
climate\precipitation\2022\PREC_2022_08.tif
climate\precipitation\2022\PREC_2022_09.tif
climate\precipitation\2022\PREC_2022_10.tif
climate\precipitation\2022\PREC_2022_11.tif
climate\precipitation\2022\PREC_2022_12.tif
climate\precipitation\2023\PREC_2023_01.tif
climate\precipitation\2023\PREC_2023_02.tif
climate\precipitation\2023\PREC_2023_03.tif
climate\precipitation\2023\PREC_2023_04.tif
climate\precipitation\2023\PREC_2023_05.tif
climate\precipitation\2023\PREC_2023_06.tif
climate\precipitation\2023\PREC_2023_07.tif
climate\precipitation\2023\PREC_2023_08.tif
climate\precipitation\2023\PREC_2023_09.tif
climate\precipitation\2023\PREC_2023_10.tif
climate\precipitation\2023\PREC_2023_11.tif
climate\precipitation\2023\PREC_2023_12.tif
climate\precipitation\2024\PREC_2024_01.tif
climate\precipitation\2024\PREC_2024_02.tif
climate\precipitation\2024\PREC_2024_03.tif
climate\precipitation\2024\PREC_2024_04.tif
climate\precipitation\2024\PREC_2024_05.tif
climate\precipitation\2024\PREC_2024_06.tif
... y 116 rásteres adicionales.

In [25]:

# CELDA 22 — AUDITORÍA DE LOS CSV ORIGINALES

from pathlib import Path
import pandas as pd

tabular_dir = Path(ROOT) / "data" / "raw" / "tabular"

archivos_csv = [
    tabular_dir / "Conjunto_datos_BASICO_AgroCebada2026.csv",
    tabular_dir / "Conjunto_datos_PRO_AgroCebada.csv",
    tabular_dir / "ID_area_rendimiento_70_30_Reto_AgroCebada.csv",
]

for archivo in archivos_csv:
    print("\n" + "=" * 90)
    print(f"ARCHIVO: {archivo.name}")

    if not archivo.exists():
        print("ERROR: archivo no encontrado.")
        continue

    df = pd.read_csv(archivo)

    print(f"Dimensiones: {df.shape[0]} filas × {df.shape[1]} columnas")
    print("\nColumnas y tipos:")
    print(df.dtypes.to_string())

    print("\nValores faltantes:")
    faltantes = df.isna().sum()
    print(faltantes[faltantes > 0].to_string() if (faltantes > 0).any()
          else "No hay valores faltantes detectados por pandas.")

    print("\nPrimeras 5 filas:")
    print(df.head().to_string(index=False))

    print("\nColumnas candidatas a identificadores:")
    candidatas_id = [
        c for c in df.columns
        if any(p in c.lower() for p in
               ["id", "parcel", "parcela", "folio", "clave"])
    ]
    print(candidatas_id if candidatas_id else "No identificadas por nombre.")

    print("\nColumnas candidatas a rendimiento:")
    candidatas_rend = [
        c for c in df.columns
        if any(p in c.lower() for p in
               ["rend", "yield", "ton", "produccion", "producción"])
    ]
    print(candidatas_rend if candidatas_rend else "No identificadas por nombre.")

==========================================================================================
ARCHIVO: Conjunto_datos_BASICO_AgroCebada2026.csv
Dimensiones: 107666 filas × 96 columnas

Columnas y tipos:
ID_POLIGONO                 str
fecha_captura               str
sensor                      str
ndvi_promedio           float64
ndvi_std                float64
ndvi_max                float64
ndvi_min                float64
evi_promedio            float64
evi_std                 float64
evi_max                 float64
evi_min                 float64
crc_promedio            float64
crc_std                 float64
crc_max                 float64
crc_min                 float64
mcrc_promedio           float64
mcrc_std                float64
mcrc_max                float64
mcrc_min                float64
ndsvi_promedio          float64
ndsvi_std               float64
ndsvi_max               float64
ndsvi_min               float64
srndi_promedio          float64
srndi_std               float64
srndi_max               float64
srndi_min               float64
mra_promedio            float64
mra_std                 float64
mra_max                 float64
mra_min                 float64
lai_promedio            float64
lai_std                 float64
lai_max                 float64
lai_min                 float64
fapar_promedio          float64
fapar_std               float64
fapar_max               float64
fapar_min               float64
savi_promedio           float64
savi_std                float64
savi_max                float64
savi_min                float64
vi6t_promedio           float64
vi6t_std                float64
vi6t_max                float64
vi6t_min                float64
ndti_promedio           float64
ndti_std                float64
ndti_max                float64
ndti_min                float64
sti_promedio            float64
sti_std                 float64
sti_max                 float64
sti_min                 float64
ndwi_promedio           float64
ndwi_std                float64
ndwi_max                float64
ndwi_min                float64
endwi_promedio          float64
endwi_std               float64
endwi_max               float64
endwi_min               float64
msi_promedio            float64
msi_std                 float64
msi_max                 float64
msi_min                 float64
emsi_promedio           float64
emsi_std                float64
emsi_max                float64
emsi_min                float64
dswi2_promedio          float64
dswi2_std               float64
dswi2_max               float64
dswi2_min               float64
dswi3_promedio          float64
dswi3_std               float64
dswi3_max               float64
dswi3_min               float64
dswi4_promedio          float64
dswi4_std               float64
dswi4_max               float64
dswi4_min               float64
dswi5_promedio          float64
dswi5_std               float64
dswi5_max               float64
dswi5_min               float64
nddi_promedio           float64
nddi_std                float64
nddi_max                float64
nddi_min                float64
enddi_promedio          float64
enddi_std               float64
enddi_max               float64
enddi_min               float64
porcentaje_nubosidad    float64

Valores faltantes:
ndvi_promedio           62789
ndvi_std                62789
ndvi_max                62789
ndvi_min                62789
evi_promedio            62789
evi_std                 62789
evi_max                 62789
evi_min                 62789
crc_promedio            62789
crc_std                 62789
crc_max                 62789
crc_min                 62789
mcrc_promedio           62789
mcrc_std                62789
mcrc_max                62789
mcrc_min                62789
ndsvi_promedio          62789
ndsvi_std               62789
ndsvi_max               62789
ndsvi_min               62789
srndi_promedio          62789
srndi_std               62789
srndi_max               62789
srndi_min               62789
mra_promedio            62789
mra_std                 62789
mra_max                 62789
mra_min                 62789
lai_promedio            62789
lai_std                 62789
lai_max                 62789
lai_min                 62789
fapar_promedio          62793
fapar_std               62793
fapar_max               62793
fapar_min               62793
savi_promedio           62789
savi_std                62789
savi_max                62789
savi_min                62789
vi6t_promedio           76618
vi6t_std                76618
vi6t_max                76618
vi6t_min                76618
ndti_promedio           62789
ndti_std                62789
ndti_max                62789
ndti_min                62789
sti_promedio            62789
sti_std                 62789
sti_max                 62789
sti_min                 62789
ndwi_promedio           62789
ndwi_std                62789
ndwi_max                62789
ndwi_min                62789
endwi_promedio          62789
endwi_std               62789
endwi_max               62789
endwi_min               62789
msi_promedio            62789
msi_std                 62789
msi_max                 62789
msi_min                 62789
emsi_promedio           62789
emsi_std                62789
emsi_max                62789
emsi_min                62789
dswi2_promedio          62789
dswi2_std               62789
dswi2_max               62789
dswi2_min               62789
dswi3_promedio          62789
dswi3_std               62789
dswi3_max               62789
dswi3_min               62789
dswi4_promedio          62789
dswi4_std               62789
dswi4_max               62789
dswi4_min               62789
dswi5_promedio          62789
dswi5_std               62789
dswi5_max               62789
dswi5_min               62789
nddi_promedio           62789
nddi_std                62789
nddi_max                62789
nddi_min                62789
enddi_promedio          62789
enddi_std               62789
enddi_max               62789
enddi_min               62789
porcentaje_nubosidad     3056

Primeras 5 filas:
ID_POLIGONO fecha_captura  sensor  ndvi_promedio  ndvi_std  ndvi_max  ndvi_min  evi_promedio  evi_std  evi_max  evi_min  crc_promedio  crc_std  crc_max  crc_min  mcrc_promedio  mcrc_std  mcrc_max  mcrc_min  ndsvi_promedio  ndsvi_std  ndsvi_max  ndsvi_min  srndi_promedio  srndi_std  srndi_max  srndi_min  mra_promedio  mra_std  mra_max  mra_min  lai_promedio  lai_std  lai_max  lai_min  fapar_promedio  fapar_std  fapar_max  fapar_min  savi_promedio  savi_std  savi_max  savi_min  vi6t_promedio  vi6t_std  vi6t_max  vi6t_min  ndti_promedio  ndti_std  ndti_max  ndti_min  sti_promedio  sti_std  sti_max  sti_min  ndwi_promedio  ndwi_std  ndwi_max  ndwi_min  endwi_promedio  endwi_std  endwi_max  endwi_min  msi_promedio  msi_std  msi_max  msi_min  emsi_promedio  emsi_std  emsi_max  emsi_min  dswi2_promedio  dswi2_std  dswi2_max  dswi2_min  dswi3_promedio  dswi3_std  dswi3_max  dswi3_min  dswi4_promedio  dswi4_std  dswi4_max  dswi4_min  dswi5_promedio  dswi5_std  dswi5_max  dswi5_min  nddi_promedio  nddi_std  nddi_max  nddi_min  enddi_promedio  enddi_std  enddi_max  enddi_min  porcentaje_nubosidad
    AGC_011    20/04/2022 Landsat            NaN       NaN       NaN       NaN           NaN      NaN      NaN      NaN           NaN      NaN      NaN      NaN            NaN       NaN       NaN       NaN             NaN        NaN        NaN        NaN             NaN        NaN        NaN        NaN           NaN      NaN      NaN      NaN           NaN      NaN      NaN      NaN             NaN        NaN        NaN        NaN            NaN       NaN       NaN       NaN         -0.613     0.018    -0.561    -0.678            NaN       NaN       NaN       NaN           NaN      NaN      NaN      NaN            NaN       NaN       NaN       NaN             NaN        NaN        NaN        NaN           NaN      NaN      NaN      NaN            NaN       NaN       NaN       NaN             NaN        NaN        NaN        NaN             NaN        NaN        NaN        NaN             NaN        NaN        NaN        NaN             NaN        NaN        NaN        NaN            NaN       NaN       NaN       NaN             NaN        NaN        NaN        NaN                   0.0
    AGC_011    16/03/2024 Landsat            NaN       NaN       NaN       NaN           NaN      NaN      NaN      NaN           NaN      NaN      NaN      NaN            NaN       NaN       NaN       NaN             NaN        NaN        NaN        NaN             NaN        NaN        NaN        NaN           NaN      NaN      NaN      NaN           NaN      NaN      NaN      NaN             NaN        NaN        NaN        NaN            NaN       NaN       NaN       NaN         -0.626     0.014    -0.590    -0.679            NaN       NaN       NaN       NaN           NaN      NaN      NaN      NaN            NaN       NaN       NaN       NaN             NaN        NaN        NaN        NaN           NaN      NaN      NaN      NaN            NaN       NaN       NaN       NaN             NaN        NaN        NaN        NaN             NaN        NaN        NaN        NaN             NaN        NaN        NaN        NaN             NaN        NaN        NaN        NaN            NaN       NaN       NaN       NaN             NaN        NaN        NaN        NaN                   0.0
    AGC_011    15/03/2024 Landsat            NaN       NaN       NaN       NaN           NaN      NaN      NaN      NaN           NaN      NaN      NaN      NaN            NaN       NaN       NaN       NaN             NaN        NaN        NaN        NaN             NaN        NaN        NaN        NaN           NaN      NaN      NaN      NaN           NaN      NaN      NaN      NaN             NaN        NaN        NaN        NaN            NaN       NaN       NaN       NaN         -0.635     0.014    -0.600    -0.686            NaN       NaN       NaN       NaN           NaN      NaN      NaN      NaN            NaN       NaN       NaN       NaN             NaN        NaN        NaN        NaN           NaN      NaN      NaN      NaN            NaN       NaN       NaN       NaN             NaN        NaN        NaN        NaN             NaN        NaN        NaN        NaN             NaN        NaN        NaN        NaN             NaN        NaN        NaN        NaN            NaN       NaN       NaN       NaN             NaN        NaN        NaN        NaN                   0.0
    AGC_011    26/08/2025 Landsat            NaN       NaN       NaN       NaN           NaN      NaN      NaN      NaN           NaN      NaN      NaN      NaN            NaN       NaN       NaN       NaN             NaN        NaN        NaN        NaN             NaN        NaN        NaN        NaN           NaN      NaN      NaN      NaN           NaN      NaN      NaN      NaN             NaN        NaN        NaN        NaN            NaN       NaN       NaN       NaN         -0.635     0.014    -0.578    -0.674            NaN       NaN       NaN       NaN           NaN      NaN      NaN      NaN            NaN       NaN       NaN       NaN             NaN        NaN        NaN        NaN           NaN      NaN      NaN      NaN            NaN       NaN       NaN       NaN             NaN        NaN        NaN        NaN             NaN        NaN        NaN        NaN             NaN        NaN        NaN        NaN             NaN        NaN        NaN        NaN            NaN       NaN       NaN       NaN             NaN        NaN        NaN        NaN                   0.0
    AGC_011    10/03/2025 Landsat            NaN       NaN       NaN       NaN           NaN      NaN      NaN      NaN           NaN      NaN      NaN      NaN            NaN       NaN       NaN       NaN             NaN        NaN        NaN        NaN             NaN        NaN        NaN        NaN           NaN      NaN      NaN      NaN           NaN      NaN      NaN      NaN             NaN        NaN        NaN        NaN            NaN       NaN       NaN       NaN         -0.644     0.015    -0.590    -0.689            NaN       NaN       NaN       NaN           NaN      NaN      NaN      NaN            NaN       NaN       NaN       NaN             NaN        NaN        NaN        NaN           NaN      NaN      NaN      NaN            NaN       NaN       NaN       NaN             NaN        NaN        NaN        NaN             NaN        NaN        NaN        NaN             NaN        NaN        NaN        NaN             NaN        NaN        NaN        NaN            NaN       NaN       NaN       NaN             NaN        NaN        NaN        NaN                   0.0

Columnas candidatas a identificadores:
['ID_POLIGONO', 'porcentaje_nubosidad']

Columnas candidatas a rendimiento:
No identificadas por nombre.

==========================================================================================
ARCHIVO: Conjunto_datos_PRO_AgroCebada.csv
Dimensiones: 47804 filas × 20 columnas

Columnas y tipos:
ID_POLIGONO                 str
fecha_captura               str
sensor                      str
ndvi_promedio           float64
ndvi_std                float64
ndvi_max                float64
ndvi_min                float64
evi_promedio            float64
evi_std                 float64
evi_max                 float64
evi_min                 float64
lai_promedio            float64
lai_std                 float64
lai_max                 float64
lai_min                 float64
msavi_promedio          float64
msavi_std               float64
msavi_max               float64
msavi_min               float64
porcentaje_nubosidad    float64

Valores faltantes:
ndvi_promedio     12057
ndvi_std          12057
ndvi_max          12057
ndvi_min          12057
evi_promedio      12057
evi_std           12057
evi_max           12057
evi_min           12057
lai_promedio      12057
lai_std           12057
lai_max           12057
lai_min           12057
msavi_promedio    12057
msavi_std         12057
msavi_max         12057
msavi_min         12057

Primeras 5 filas:
ID_POLIGONO fecha_captura sensor  ndvi_promedio  ndvi_std  ndvi_max  ndvi_min  evi_promedio  evi_std  evi_max  evi_min  lai_promedio  lai_std  lai_max  lai_min  msavi_promedio  msavi_std  msavi_max  msavi_min  porcentaje_nubosidad
    AGC_056    05/02/2025 Planet          0.300     0.042     0.553     0.175         0.138    0.022    0.251    0.068         1.049    0.182    2.144    0.586           0.135      0.022      0.244      0.066                   0.0
    AGC_056    08/02/2025 Planet          0.204     0.043     0.529     0.125         0.110    0.018    0.209    0.074         0.697    0.167    1.888    0.247           0.110      0.018      0.207      0.072                   0.0
    AGC_056    07/02/2025 Planet          0.241     0.043     0.534     0.154         0.134    0.018    0.224    0.098         0.826    0.159    1.858    0.404           0.135      0.018      0.230      0.098                   0.0
    AGC_056    09/02/2025 Planet          0.246     0.039     0.536     0.153         0.142    0.018    0.243    0.098         0.818    0.159    1.849    0.399           0.141      0.018      0.237      0.095                   0.0
    AGC_056    30/01/2025 Planet          0.211     0.046     0.533     0.113         0.110    0.020    0.229    0.069         0.724    0.187    1.955    0.277           0.111      0.021      0.230      0.067                   0.0

Columnas candidatas a identificadores:
['ID_POLIGONO', 'porcentaje_nubosidad']

Columnas candidatas a rendimiento:
No identificadas por nombre.

==========================================================================================
ARCHIVO: ID_area_rendimiento_70_30_Reto_AgroCebada.csv
Dimensiones: 197 filas × 5 columnas

Columnas y tipos:
ID_POLIGONO             str
AREA_HA             float64
RENDIMIENTO_T_HA    float64
CONJUNTO                str
Unnamed: 4          float64

Valores faltantes:
RENDIMIENTO_T_HA     59
Unnamed: 4          197

Primeras 5 filas:
ID_POLIGONO  AREA_HA  RENDIMIENTO_T_HA      CONJUNTO  Unnamed: 4
    AGC_001     7.61              3.50 ENTRENAMIENTO         NaN
    AGC_002     2.31              4.63 ENTRENAMIENTO         NaN
    AGC_003    18.68               NaN    PREDICCION         NaN
    AGC_004     8.00              3.00 ENTRENAMIENTO         NaN
    AGC_005     2.27              5.16 ENTRENAMIENTO         NaN

Columnas candidatas a identificadores:
['ID_POLIGONO']

Columnas candidatas a rendimiento:
['RENDIMIENTO_T_HA']

In [26]:

# CELDA 23 — AUDITORÍA DE PARCELAS, FECHAS Y RENDIMIENTO

from pathlib import Path
import pandas as pd

tabular_dir = Path(ROOT) / "data" / "raw" / "tabular"

basico_path = tabular_dir / "Conjunto_datos_BASICO_AgroCebada2026.csv"
pro_path = tabular_dir / "Conjunto_datos_PRO_AgroCebada.csv"
rend_path = tabular_dir / "ID_area_rendimiento_70_30_Reto_AgroCebada.csv"

basico = pd.read_csv(basico_path)
pro = pd.read_csv(pro_path)
rend = pd.read_csv(rend_path)

# Normalizar IDs solo para la auditoría; no modificar los archivos fuente.
for df in (basico, pro, rend):
    df["ID_POLIGONO"] = df["ID_POLIGONO"].astype("string").str.strip()

for df in (basico, pro):
    df["fecha_captura"] = pd.to_datetime(
        df["fecha_captura"], dayfirst=True, errors="coerce"
    )

ids_basico = set(basico["ID_POLIGONO"].dropna().unique())
ids_pro = set(pro["ID_POLIGONO"].dropna().unique())
ids_rend = set(rend["ID_POLIGONO"].dropna().unique())

ids_objetivo = set(
    rend.loc[rend["RENDIMIENTO_T_HA"].notna(), "ID_POLIGONO"]
)
ids_prediccion = set(
    rend.loc[rend["RENDIMIENTO_T_HA"].isna(), "ID_POLIGONO"]
)

print("=== PARTICIÓN DE RENDIMIENTO ===")
print("Parcelas totales:", rend["ID_POLIGONO"].nunique())
print("Con rendimiento:", len(ids_objetivo))
print("Sin rendimiento:", len(ids_prediccion))
print("\nCONJUNTO:")
print(rend["CONJUNTO"].value_counts(dropna=False).to_string())

print("\n=== COBERTURA DE IDS ===")
for nombre, ids in [
    ("BASIC", ids_basico),
    ("PRO", ids_pro),
]:
    print(f"\n{nombre}")
    print("IDs únicos:", len(ids))
    print("IDs del archivo de rendimiento presentes:", len(ids & ids_rend))
    print("IDs de entrenamiento presentes:", len(ids & ids_objetivo))
    print("IDs de predicción presentes:", len(ids & ids_prediccion))
    print("IDs del archivo de rendimiento sin observaciones:", 
          sorted(ids_rend - ids)[:20])

print("\n=== RESUMEN TEMPORAL Y POR SENSOR ===")
for nombre, df in [("BASIC", basico), ("PRO", pro)]:
    print(f"\n{nombre}")
    print("Fechas inválidas:", int(df["fecha_captura"].isna().sum()))
    print("Fecha mínima:", df["fecha_captura"].min())
    print("Fecha máxima:", df["fecha_captura"].max())
    print("Registros por sensor:")
    print(df["sensor"].value_counts(dropna=False).to_string())

    por_parcela = df.groupby("ID_POLIGONO").agg(
        observaciones=("fecha_captura", "size"),
        fechas_validas=("fecha_captura", "count"),
        fechas_distintas=("fecha_captura", "nunique"),
    )

    print("\nObservaciones por parcela:")
    print(por_parcela["observaciones"].describe().round(2).to_string())

    duplicados = df.duplicated(
        subset=["ID_POLIGONO", "fecha_captura", "sensor"],
        keep=False
    )
    print("\nFilas que comparten ID, fecha y sensor:", int(duplicados.sum()))

print("\n=== CONTROL DEL ARCHIVO DE RENDIMIENTO ===")
print("IDs duplicados:", int(rend["ID_POLIGONO"].duplicated().sum()))
print("Rendimientos negativos:",
      int((rend["RENDIMIENTO_T_HA"].dropna() < 0).sum()))
print("Particiones desconocidas:",
      sorted(set(rend["CONJUNTO"].dropna().astype(str)) -
             {"ENTRENAMIENTO", "PREDICCION"}))

print("\nAuditoría terminada. Los archivos originales no fueron modificados.")

=== PARTICIÓN DE RENDIMIENTO ===
Parcelas totales: 197
Con rendimiento: 138
Sin rendimiento: 59

CONJUNTO:
CONJUNTO
ENTRENAMIENTO    138
PREDICCION        59

=== COBERTURA DE IDS ===

BASIC
IDs únicos: 197
IDs del archivo de rendimiento presentes: 197
IDs de entrenamiento presentes: 138
IDs de predicción presentes: 59
IDs del archivo de rendimiento sin observaciones: []

PRO
IDs únicos: 197
IDs del archivo de rendimiento presentes: 197
IDs de entrenamiento presentes: 138
IDs de predicción presentes: 59
IDs del archivo de rendimiento sin observaciones: []

=== RESUMEN TEMPORAL Y POR SENSOR ===

BASIC
Fechas inválidas: 0
Fecha mínima: 2022-01-01 00:00:00
Fecha máxima: 2025-12-31 00:00:00
Registros por sensor:
sensor
Sentinel-2    59040
Landsat       48626

Observaciones por parcela:
count    197.00
mean     546.53
std       65.28
min      494.00
25%      504.00
50%      511.00
75%      573.00
max      692.00

Filas que comparten ID, fecha y sensor: 0

PRO
Fechas inválidas: 0
Fecha mínima: 2025-01-01 00:00:00
Fecha máxima: 2025-12-30 00:00:00
Registros por sensor:
sensor
Planet    47804

Observaciones por parcela:
count    197.00
mean     242.66
std        4.42
min      233.00
25%      240.00
50%      243.00
75%      246.00
max      251.00

Filas que comparten ID, fecha y sensor: 0

=== CONTROL DEL ARCHIVO DE RENDIMIENTO ===
IDs duplicados: 0
Rendimientos negativos: 0
Particiones desconocidas: []

Auditoría terminada. Los archivos originales no fueron modificados.

In [27]:

# CELDA 24 — DIAGNÓSTICO TEMPORAL Y CALIDAD DE LOS DATOS

import pandas as pd
from pathlib import Path

tabular_dir = Path(ROOT) / "data" / "raw" / "tabular"

basico = pd.read_csv(
    tabular_dir / "Conjunto_datos_BASICO_AgroCebada2026.csv"
)
pro = pd.read_csv(
    tabular_dir / "Conjunto_datos_PRO_AgroCebada.csv"
)

for df in (basico, pro):
    df["fecha_captura"] = pd.to_datetime(
        df["fecha_captura"], dayfirst=True, errors="coerce"
    )
    df["año"] = df["fecha_captura"].dt.year
    df["mes"] = df["fecha_captura"].dt.month

# 1. Cantidad de observaciones por año y sensor
print("=" * 80)
print("1. OBSERVACIONES POR AÑO Y SENSOR")

for nombre, df in [("BASIC", basico), ("PRO", pro)]:
    print(f"\n--- {nombre} ---")
    print(
        df.groupby(["año", "sensor"], dropna=False)
          .size()
          .unstack(fill_value=0)
          .to_string()
    )

# 2. Cobertura mensual por año y sensor
print("\n" + "=" * 80)
print("2. MESES CON OBSERVACIONES POR AÑO Y SENSOR")

for nombre, df in [("BASIC", basico), ("PRO", pro)]:
    print(f"\n--- {nombre} ---")
    cobertura = (
        df.groupby(["año", "sensor"])["mes"]
          .nunique()
          .rename("meses_con_observaciones")
    )
    print(cobertura.to_string())

# 3. Proporción de valores faltantes por sensor
print("\n" + "=" * 80)
print("3. VALORES FALTANTES POR SENSOR")

columnas_numericas_basico = [
    c for c in basico.select_dtypes(include="number").columns
    if c not in {"año", "mes"}
]
columnas_numericas_pro = [
    c for c in pro.select_dtypes(include="number").columns
    if c not in {"año", "mes"}
]

for nombre, df, columnas in [
    ("BASIC", basico, columnas_numericas_basico),
    ("PRO", pro, columnas_numericas_pro),
]:
    print(f"\n--- {nombre} ---")
    faltantes = df.groupby("sensor")[columnas].agg(
        lambda s: s.isna().mean() * 100
    )
    print("Porcentaje de valores faltantes:")
    print(faltantes.round(1).to_string())

# 4. Distribución de registros por parcela y sensor
print("\n" + "=" * 80)
print("4. REGISTROS POR PARCELA Y SENSOR")

for nombre, df in [("BASIC", basico), ("PRO", pro)]:
    print(f"\n--- {nombre} ---")
    conteos = df.groupby(["ID_POLIGONO", "sensor"]).size()
    print(conteos.groupby("sensor").describe().round(2).to_string())

# 5. Número de observaciones completamente vacías en las variables
# espectrales, sin contar identificadores, fecha, sensor ni nubosidad.
print("\n" + "=" * 80)
print("5. FILAS SIN NINGÚN ÍNDICE ESPECTRAL DISPONIBLE")

for nombre, df in [("BASIC", basico), ("PRO", pro)]:
    excluir = {
        "ID_POLIGONO", "fecha_captura", "sensor",
        "año", "mes", "porcentaje_nubosidad"
    }
    indices = [
        c for c in df.select_dtypes(include="number").columns
        if c not in excluir
    ]

    filas_vacias = df[indices].isna().all(axis=1)

    print(
        f"{nombre}: {int(filas_vacias.sum()):,} de {len(df):,} filas "
        f"({filas_vacias.mean() * 100:.2f}%)"
    )

print("\nDiagnóstico terminado; los archivos originales no fueron modificados.")

================================================================================
1. OBSERVACIONES POR AÑO Y SENSOR

--- BASIC ---
sensor  Landsat  Sentinel-2
año
2022      12806       13922
2023      13125       13917
2024      11759       14381
2025      10936       16820

--- PRO ---
sensor  Planet
año
2025     47804

================================================================================
2. MESES CON OBSERVACIONES POR AÑO Y SENSOR

--- BASIC ---
año   sensor
2022  Landsat       12
      Sentinel-2    12
2023  Landsat       12
      Sentinel-2    12
2024  Landsat       12
      Sentinel-2    12
2025  Landsat       12
      Sentinel-2    12

--- PRO ---
año   sensor
2025  Planet    12

================================================================================
3. VALORES FALTANTES POR SENSOR

--- BASIC ---
Porcentaje de valores faltantes:
            ndvi_promedio  ndvi_std  ndvi_max  ndvi_min  evi_promedio  evi_std  evi_max  evi_min  crc_promedio  crc_std  crc_max  crc_min  mcrc_promedio  mcrc_std  mcrc_max  mcrc_min  ndsvi_promedio  ndsvi_std  ndsvi_max  ndsvi_min  srndi_promedio  srndi_std  srndi_max  srndi_min  mra_promedio  mra_std  mra_max  mra_min  lai_promedio  lai_std  lai_max  lai_min  fapar_promedio  fapar_std  fapar_max  fapar_min  savi_promedio  savi_std  savi_max  savi_min  vi6t_promedio  vi6t_std  vi6t_max  vi6t_min  ndti_promedio  ndti_std  ndti_max  ndti_min  sti_promedio  sti_std  sti_max  sti_min  ndwi_promedio  ndwi_std  ndwi_max  ndwi_min  endwi_promedio  endwi_std  endwi_max  endwi_min  msi_promedio  msi_std  msi_max  msi_min  emsi_promedio  emsi_std  emsi_max  emsi_min  dswi2_promedio  dswi2_std  dswi2_max  dswi2_min  dswi3_promedio  dswi3_std  dswi3_max  dswi3_min  dswi4_promedio  dswi4_std  dswi4_max  dswi4_min  dswi5_promedio  dswi5_std  dswi5_max  dswi5_min  nddi_promedio  nddi_std  nddi_max  nddi_min  enddi_promedio  enddi_std  enddi_max  enddi_min  porcentaje_nubosidad
sensor
Landsat             100.0     100.0     100.0     100.0         100.0    100.0    100.0    100.0         100.0    100.0    100.0    100.0          100.0     100.0     100.0     100.0           100.0      100.0      100.0      100.0           100.0      100.0      100.0      100.0         100.0    100.0    100.0    100.0         100.0    100.0    100.0    100.0           100.0      100.0      100.0      100.0          100.0     100.0     100.0     100.0           36.1      36.1      36.1      36.1          100.0     100.0     100.0     100.0         100.0    100.0    100.0    100.0          100.0     100.0     100.0     100.0           100.0      100.0      100.0      100.0         100.0    100.0    100.0    100.0          100.0     100.0     100.0     100.0           100.0      100.0      100.0      100.0           100.0      100.0      100.0      100.0           100.0      100.0      100.0      100.0           100.0      100.0      100.0      100.0          100.0     100.0     100.0     100.0           100.0      100.0      100.0      100.0                   6.3
Sentinel-2           24.0      24.0      24.0      24.0          24.0     24.0     24.0     24.0          24.0     24.0     24.0     24.0           24.0      24.0      24.0      24.0            24.0       24.0       24.0       24.0            24.0       24.0       24.0       24.0          24.0     24.0     24.0     24.0          24.0     24.0     24.0     24.0            24.0       24.0       24.0       24.0           24.0      24.0      24.0      24.0          100.0     100.0     100.0     100.0           24.0      24.0      24.0      24.0          24.0     24.0     24.0     24.0           24.0      24.0      24.0      24.0            24.0       24.0       24.0       24.0          24.0     24.0     24.0     24.0           24.0      24.0      24.0      24.0            24.0       24.0       24.0       24.0            24.0       24.0       24.0       24.0            24.0       24.0       24.0       24.0            24.0       24.0       24.0       24.0           24.0      24.0      24.0      24.0            24.0       24.0       24.0       24.0                   0.0

--- PRO ---
Porcentaje de valores faltantes:
        ndvi_promedio  ndvi_std  ndvi_max  ndvi_min  evi_promedio  evi_std  evi_max  evi_min  lai_promedio  lai_std  lai_max  lai_min  msavi_promedio  msavi_std  msavi_max  msavi_min  porcentaje_nubosidad
sensor
Planet           25.2      25.2      25.2      25.2          25.2     25.2     25.2     25.2          25.2     25.2     25.2     25.2            25.2       25.2       25.2       25.2                   0.0

================================================================================
4. REGISTROS POR PARCELA Y SENSOR

--- BASIC ---
            count    mean    std    min    25%    50%    75%    max
sensor
Landsat     197.0  246.83  64.76  195.0  205.0  211.0  272.0  391.0
Sentinel-2  197.0  299.70   1.35  298.0  298.0  300.0  301.0  301.0

--- PRO ---
        count    mean   std    min    25%    50%    75%    max
sensor
Planet  197.0  242.66  4.42  233.0  240.0  243.0  246.0  251.0

================================================================================
5. FILAS SIN NINGÚN ÍNDICE ESPECTRAL DISPONIBLE
BASIC: 31,741 de 107,666 filas (29.48%)
PRO: 12,057 de 47,804 filas (25.22%)

Diagnóstico terminado; los archivos originales no fueron modificados.

In [28]:

# CELDA 25 — DISPONIBILIDAD TEMPORAL DE ÍNDICES ESPECTRALES

import pandas as pd
from pathlib import Path

tabular_dir = Path(ROOT) / "data" / "raw" / "tabular"

basico = pd.read_csv(
    tabular_dir / "Conjunto_datos_BASICO_AgroCebada2026.csv"
)

basico["fecha_captura"] = pd.to_datetime(
    basico["fecha_captura"], dayfirst=True, errors="coerce"
)
basico["año"] = basico["fecha_captura"].dt.year
basico["mes"] = basico["fecha_captura"].dt.month

# Índices representativos que aparecen en el archivo original.
indices = [
    "ndvi_promedio",
    "evi_promedio",
    "lai_promedio",
    "savi_promedio",
    "vi6t_promedio",
    "ndwi_promedio",
    "ndti_promedio",
]

print("=== DISPONIBILIDAD POR AÑO Y SENSOR ===")

for indice in indices:
    print(f"\n--- {indice} ---")

    disponibilidad = (
        basico.groupby(["año", "sensor"])[indice]
        .agg(
            registros="size",
            validos="count",
        )
        .reset_index()
    )

    disponibilidad["porcentaje_valido"] = (
        disponibilidad["validos"] /
        disponibilidad["registros"] * 100
    )

    print(
        disponibilidad.to_string(
            index=False,
            formatters={
                "porcentaje_valido": lambda x: f"{x:.1f}%"
            }
        )
    )

print("\n=== DISPONIBILIDAD MENSUAL DE NDVI ===")

ndvi_mensual = (
    basico.groupby(["sensor", "año", "mes"])["ndvi_promedio"]
    .agg(registros="size", validos="count")
    .reset_index()
)

ndvi_mensual["porcentaje_valido"] = (
    ndvi_mensual["validos"] /
    ndvi_mensual["registros"] * 100
)

print(
    ndvi_mensual.to_string(
        index=False,
        formatters={
            "porcentaje_valido": lambda x: f"{x:.1f}%"
        }
    )
)

print("\nAuditoría terminada; no se modificaron los datos originales.")

=== DISPONIBILIDAD POR AÑO Y SENSOR ===

--- ndvi_promedio ---
 año     sensor  registros  validos porcentaje_valido
2022    Landsat      12806        0              0.0%
2022 Sentinel-2      13922    10045             72.2%
2023    Landsat      13125        0              0.0%
2023 Sentinel-2      13917    10301             74.0%
2024    Landsat      11759        0              0.0%
2024 Sentinel-2      14381    11440             79.5%
2025    Landsat      10936        0              0.0%
2025 Sentinel-2      16820    13091             77.8%

--- evi_promedio ---
 año     sensor  registros  validos porcentaje_valido
2022    Landsat      12806        0              0.0%
2022 Sentinel-2      13922    10045             72.2%
2023    Landsat      13125        0              0.0%
2023 Sentinel-2      13917    10301             74.0%
2024    Landsat      11759        0              0.0%
2024 Sentinel-2      14381    11440             79.5%
2025    Landsat      10936        0              0.0%
2025 Sentinel-2      16820    13091             77.8%

--- lai_promedio ---
 año     sensor  registros  validos porcentaje_valido
2022    Landsat      12806        0              0.0%
2022 Sentinel-2      13922    10045             72.2%
2023    Landsat      13125        0              0.0%
2023 Sentinel-2      13917    10301             74.0%
2024    Landsat      11759        0              0.0%
2024 Sentinel-2      14381    11440             79.5%
2025    Landsat      10936        0              0.0%
2025 Sentinel-2      16820    13091             77.8%

--- savi_promedio ---
 año     sensor  registros  validos porcentaje_valido
2022    Landsat      12806        0              0.0%
2022 Sentinel-2      13922    10045             72.2%
2023    Landsat      13125        0              0.0%
2023 Sentinel-2      13917    10301             74.0%
2024    Landsat      11759        0              0.0%
2024 Sentinel-2      14381    11440             79.5%
2025    Landsat      10936        0              0.0%
2025 Sentinel-2      16820    13091             77.8%

--- vi6t_promedio ---
 año     sensor  registros  validos porcentaje_valido
2022    Landsat      12806     7857             61.4%
2022 Sentinel-2      13922        0              0.0%
2023    Landsat      13125     8139             62.0%
2023 Sentinel-2      13917        0              0.0%
2024    Landsat      11759     7739             65.8%
2024 Sentinel-2      14381        0              0.0%
2025    Landsat      10936     7313             66.9%
2025 Sentinel-2      16820        0              0.0%

--- ndwi_promedio ---
 año     sensor  registros  validos porcentaje_valido
2022    Landsat      12806        0              0.0%
2022 Sentinel-2      13922    10045             72.2%
2023    Landsat      13125        0              0.0%
2023 Sentinel-2      13917    10301             74.0%
2024    Landsat      11759        0              0.0%
2024 Sentinel-2      14381    11440             79.5%
2025    Landsat      10936        0              0.0%
2025 Sentinel-2      16820    13091             77.8%

--- ndti_promedio ---
 año     sensor  registros  validos porcentaje_valido
2022    Landsat      12806        0              0.0%
2022 Sentinel-2      13922    10045             72.2%
2023    Landsat      13125        0              0.0%
2023 Sentinel-2      13917    10301             74.0%
2024    Landsat      11759        0              0.0%
2024 Sentinel-2      14381    11440             79.5%
2025    Landsat      10936        0              0.0%
2025 Sentinel-2      16820    13091             77.8%

=== DISPONIBILIDAD MENSUAL DE NDVI ===
    sensor  año  mes  registros  validos porcentaje_valido
   Landsat 2022    1        909        0              0.0%
   Landsat 2022    2        701        0              0.0%
   Landsat 2022    3        736        0              0.0%
   Landsat 2022    4       1062        0              0.0%
   Landsat 2022    5       1271        0              0.0%
   Landsat 2022    6       1288        0              0.0%
   Landsat 2022    7        948        0              0.0%
   Landsat 2022    8       1118        0              0.0%
   Landsat 2022    9       1042        0              0.0%
   Landsat 2022   10       1187        0              0.0%
   Landsat 2022   11       1281        0              0.0%
   Landsat 2022   12       1263        0              0.0%
   Landsat 2023    1        774        0              0.0%
   Landsat 2023    2       1456        0              0.0%
   Landsat 2023    3        938        0              0.0%
   Landsat 2023    4       1285        0              0.0%
   Landsat 2023    5       1016        0              0.0%
   Landsat 2023    6       1031        0              0.0%
   Landsat 2023    7       1203        0              0.0%
   Landsat 2023    8       1218        0              0.0%
   Landsat 2023    9       1165        0              0.0%
   Landsat 2023   10       1129        0              0.0%
   Landsat 2023   11        935        0              0.0%
   Landsat 2023   12        975        0              0.0%
   Landsat 2024    1       1097        0              0.0%
   Landsat 2024    2       1118        0              0.0%
   Landsat 2024    3        980        0              0.0%
   Landsat 2024    4        922        0              0.0%
   Landsat 2024    5       1004        0              0.0%
   Landsat 2024    6        957        0              0.0%
   Landsat 2024    7       1044        0              0.0%
   Landsat 2024    8        987        0              0.0%
   Landsat 2024    9        698        0              0.0%
   Landsat 2024   10       1010        0              0.0%
   Landsat 2024   11        996        0              0.0%
   Landsat 2024   12        946        0              0.0%
   Landsat 2025    1        954        0              0.0%
   Landsat 2025    2        801        0              0.0%
   Landsat 2025    3        957        0              0.0%
   Landsat 2025    4       1021        0              0.0%
   Landsat 2025    5       1028        0              0.0%
   Landsat 2025    6        907        0              0.0%
   Landsat 2025    7        717        0              0.0%
   Landsat 2025    8        927        0              0.0%
   Landsat 2025    9        961        0              0.0%
   Landsat 2025   10        749        0              0.0%
   Landsat 2025   11        971        0              0.0%
   Landsat 2025   12        943        0              0.0%
Sentinel-2 2022    1       1379     1060             76.9%
Sentinel-2 2022    2        985      918             93.2%
Sentinel-2 2022    3       1182      970             82.1%
Sentinel-2 2022    4       1117      890             79.7%
Sentinel-2 2022    5       1379     1109             80.4%
Sentinel-2 2022    6       1182      794             67.2%
Sentinel-2 2022    7       1182      787             66.6%
Sentinel-2 2022    8       1182      549             46.4%
Sentinel-2 2022    9       1182      261             22.1%
Sentinel-2 2022   10       1182      785             66.4%
Sentinel-2 2022   11        985      942             95.6%
Sentinel-2 2022   12        985      980             99.5%
Sentinel-2 2023    1       1379     1349             97.8%
Sentinel-2 2023    2        985      926             94.0%
Sentinel-2 2023    3       1182     1165             98.6%
Sentinel-2 2023    4       1182      825             69.8%
Sentinel-2 2023    5       1147      914             79.7%
Sentinel-2 2023    6       1182      881             74.5%
Sentinel-2 2023    7       1182      741             62.7%
Sentinel-2 2023    8       1182      430             36.4%
Sentinel-2 2023    9       1147      985             85.9%
Sentinel-2 2023   10        985      715             72.6%
Sentinel-2 2023   11       1182      650             55.0%
Sentinel-2 2023   12       1182      720             60.9%
Sentinel-2 2024    1       1379      962             69.8%
Sentinel-2 2024    2        985      984             99.9%
Sentinel-2 2024    3       1379     1379            100.0%
Sentinel-2 2024    4       1182     1111             94.0%
Sentinel-2 2024    5       1182     1111             94.0%
Sentinel-2 2024    6       1182      846             71.6%
Sentinel-2 2024    7       1182      697             59.0%
Sentinel-2 2024    8       1182      854             72.3%
Sentinel-2 2024    9        985      426             43.2%
Sentinel-2 2024   10       1182      618             52.3%
Sentinel-2 2024   11       1182     1139             96.4%
Sentinel-2 2024   12       1379     1313             95.2%
Sentinel-2 2025    1       1182      922             78.0%
Sentinel-2 2025    2        985      758             77.0%
Sentinel-2 2025    3       1576     1423             90.3%
Sentinel-2 2025    4       1576     1530             97.1%
Sentinel-2 2025    5       1379      911             66.1%
Sentinel-2 2025    6       1576      631             40.0%
Sentinel-2 2025    7       1379     1106             80.2%
Sentinel-2 2025    8       1379     1291             93.6%
Sentinel-2 2025    9       1318      854             64.8%
Sentinel-2 2025   10       1379     1029             74.6%
Sentinel-2 2025   11       1515     1498             98.9%
Sentinel-2 2025   12       1576     1138             72.2%

Auditoría terminada; no se modificaron los datos originales.

In [29]:

# CELDA 26 — INSPECCIÓN DIRECTA DE REGISTROS LANDSAT

from pathlib import Path
import pandas as pd

archivo = (
    Path(ROOT) / "data" / "raw" / "tabular"
    / "Conjunto_datos_BASICO_AgroCebada2026.csv"
)

df = pd.read_csv(archivo)
landsat = df[df["sensor"].eq("Landsat")].copy()

columnas = [
    "ID_POLIGONO",
    "fecha_captura",
    "sensor",
    "ndvi_promedio",
    "evi_promedio",
    "lai_promedio",
    "savi_promedio",
    "vi6t_promedio",
    "ndwi_promedio",
    "ndti_promedio",
    "porcentaje_nubosidad",
]

print("=== MUESTRA DE REGISTROS LANDSAT ===")
print(landsat[columnas].head(15).to_string(index=False))

print("\n=== ESTADÍSTICAS DE LAS VARIABLES ===")
variables = [
    c for c in columnas
    if c not in {"ID_POLIGONO", "fecha_captura", "sensor"}
]

print(landsat[variables].describe().T.to_string())

print("\n=== CONTEO DE VALORES DISTINTOS ===")
for c in variables:
    print(
        f"{c}: "
        f"válidos={landsat[c].notna().sum()}, "
        f"distintos={landsat[c].nunique(dropna=True)}"
    )

print("\n=== COMPARACIÓN CON SENTINEL-2 ===")
sentinel = df[df["sensor"].eq("Sentinel-2")]

for c in ["ndvi_promedio", "evi_promedio", "lai_promedio", "vi6t_promedio"]:
    print(
        f"{c}: "
        f"Landsat válidos={landsat[c].notna().sum()}, "
        f"Sentinel-2 válidos={sentinel[c].notna().sum()}"
    )

=== MUESTRA DE REGISTROS LANDSAT ===
ID_POLIGONO fecha_captura  sensor  ndvi_promedio  evi_promedio  lai_promedio  savi_promedio  vi6t_promedio  ndwi_promedio  ndti_promedio  porcentaje_nubosidad
    AGC_011    20/04/2022 Landsat            NaN           NaN           NaN            NaN         -0.613            NaN            NaN                  0.00
    AGC_011    16/03/2024 Landsat            NaN           NaN           NaN            NaN         -0.626            NaN            NaN                  0.00
    AGC_011    15/03/2024 Landsat            NaN           NaN           NaN            NaN         -0.635            NaN            NaN                  0.00
    AGC_011    26/08/2025 Landsat            NaN           NaN           NaN            NaN         -0.635            NaN            NaN                  0.00
    AGC_011    10/03/2025 Landsat            NaN           NaN           NaN            NaN         -0.644            NaN            NaN                  0.00
    AGC_011    04/10/2022 Landsat            NaN           NaN           NaN            NaN         -0.646            NaN            NaN                  7.69
    AGC_011    11/03/2025 Landsat            NaN           NaN           NaN            NaN         -0.634            NaN            NaN                  0.00
    AGC_011    02/03/2025 Landsat            NaN           NaN           NaN            NaN         -0.644            NaN            NaN                  0.00
    AGC_011    17/08/2025 Landsat            NaN           NaN           NaN            NaN         -0.637            NaN            NaN                  0.00
    AGC_011    03/03/2025 Landsat            NaN           NaN           NaN            NaN         -0.639            NaN            NaN                  0.00
    AGC_011    18/08/2025 Landsat            NaN           NaN           NaN            NaN         -0.620            NaN            NaN                  0.00
    AGC_011    23/03/2024 Landsat            NaN           NaN           NaN            NaN         -0.632            NaN            NaN                  0.00
    AGC_011    30/08/2024 Landsat            NaN           NaN           NaN            NaN         -0.626            NaN            NaN                  0.00
    AGC_011    14/09/2023 Landsat            NaN           NaN           NaN            NaN         -0.581            NaN            NaN                 10.58
    AGC_011    19/04/2022 Landsat            NaN           NaN           NaN            NaN         -0.616            NaN            NaN                  0.00

=== ESTADÍSTICAS DE LAS VARIABLES ===
                        count       mean        std    min    25%    50%      75%      max
ndvi_promedio             0.0        NaN        NaN    NaN    NaN    NaN      NaN      NaN
evi_promedio              0.0        NaN        NaN    NaN    NaN    NaN      NaN      NaN
lai_promedio              0.0        NaN        NaN    NaN    NaN    NaN      NaN      NaN
savi_promedio             0.0        NaN        NaN    NaN    NaN    NaN      NaN      NaN
vi6t_promedio         31048.0  -0.620601   0.025795 -0.802 -0.638 -0.625   -0.608   -0.431
ndwi_promedio             0.0        NaN        NaN    NaN    NaN    NaN      NaN      NaN
ndti_promedio             0.0        NaN        NaN    NaN    NaN    NaN      NaN      NaN
porcentaje_nubosidad  45570.0  36.216807  46.706084  0.000  0.000  0.000  100.000  100.000

=== CONTEO DE VALORES DISTINTOS ===
ndvi_promedio: válidos=0, distintos=0
evi_promedio: válidos=0, distintos=0
lai_promedio: válidos=0, distintos=0
savi_promedio: válidos=0, distintos=0
vi6t_promedio: válidos=31048, distintos=229
ndwi_promedio: válidos=0, distintos=0
ndti_promedio: válidos=0, distintos=0
porcentaje_nubosidad: válidos=45570, distintos=2251

=== COMPARACIÓN CON SENTINEL-2 ===
ndvi_promedio: Landsat válidos=0, Sentinel-2 válidos=44877
evi_promedio: Landsat válidos=0, Sentinel-2 válidos=44877
lai_promedio: Landsat válidos=0, Sentinel-2 válidos=44877
vi6t_promedio: Landsat válidos=31048, Sentinel-2 válidos=0

In [30]:

# CELDA 27 — MATRIZ DE DISPONIBILIDAD POR SENSOR

from pathlib import Path
import pandas as pd

archivo = (
    Path(ROOT) / "data" / "raw" / "tabular"
    / "Conjunto_datos_BASICO_AgroCebada2026.csv"
)

df = pd.read_csv(archivo)

excluir = {
    "ID_POLIGONO",
    "fecha_captura",
    "sensor",
}

variables = [
    c for c in df.columns
    if c not in excluir
    and pd.api.types.is_numeric_dtype(df[c])
]

resumen = []

for sensor, grupo in df.groupby("sensor"):
    for variable in variables:
        resumen.append({
            "sensor": sensor,
            "variable": variable,
            "registros": len(grupo),
            "validos": int(grupo[variable].notna().sum()),
            "porcentaje_valido": (
                grupo[variable].notna().mean() * 100
            ),
            "valores_distintos": grupo[variable].nunique(
                dropna=True
            ),
        })

disponibilidad = pd.DataFrame(resumen)

tabla = disponibilidad.pivot(
    index="variable",
    columns="sensor",
    values="porcentaje_valido"
).fillna(0)

print("=== PORCENTAJE DE VALORES VÁLIDOS POR SENSOR ===")
print(tabla.round(1).to_string())

print("\n=== VARIABLES CON DATOS EXCLUSIVOS DE CADA SENSOR ===")

for sensor in sorted(df["sensor"].dropna().unique()):
    exclusivas = disponibilidad[
        (disponibilidad["sensor"] == sensor)
        & (disponibilidad["porcentaje_valido"] > 0)
    ]["variable"].tolist()

    print(f"\n{sensor}:")
    print(exclusivas)

print("\n=== VARIABLES COMPLETAMENTE VACÍAS ===")
for sensor in sorted(df["sensor"].dropna().unique()):
    vacias = disponibilidad[
        (disponibilidad["sensor"] == sensor)
        & (disponibilidad["validos"] == 0)
    ]["variable"].tolist()

    print(f"\n{sensor}: {vacias}")

print("\nAuditoría terminada; no se modificaron los datos originales.")

=== PORCENTAJE DE VALORES VÁLIDOS POR SENSOR ===
sensor                Landsat  Sentinel-2
variable
crc_max                   0.0        76.0
crc_min                   0.0        76.0
crc_promedio              0.0        76.0
crc_std                   0.0        76.0
dswi2_max                 0.0        76.0
dswi2_min                 0.0        76.0
dswi2_promedio            0.0        76.0
dswi2_std                 0.0        76.0
dswi3_max                 0.0        76.0
dswi3_min                 0.0        76.0
dswi3_promedio            0.0        76.0
dswi3_std                 0.0        76.0
dswi4_max                 0.0        76.0
dswi4_min                 0.0        76.0
dswi4_promedio            0.0        76.0
dswi4_std                 0.0        76.0
dswi5_max                 0.0        76.0
dswi5_min                 0.0        76.0
dswi5_promedio            0.0        76.0
dswi5_std                 0.0        76.0
emsi_max                  0.0        76.0
emsi_min                  0.0        76.0
emsi_promedio             0.0        76.0
emsi_std                  0.0        76.0
enddi_max                 0.0        76.0
enddi_min                 0.0        76.0
enddi_promedio            0.0        76.0
enddi_std                 0.0        76.0
endwi_max                 0.0        76.0
endwi_min                 0.0        76.0
endwi_promedio            0.0        76.0
endwi_std                 0.0        76.0
evi_max                   0.0        76.0
evi_min                   0.0        76.0
evi_promedio              0.0        76.0
evi_std                   0.0        76.0
fapar_max                 0.0        76.0
fapar_min                 0.0        76.0
fapar_promedio            0.0        76.0
fapar_std                 0.0        76.0
lai_max                   0.0        76.0
lai_min                   0.0        76.0
lai_promedio              0.0        76.0
lai_std                   0.0        76.0
mcrc_max                  0.0        76.0
mcrc_min                  0.0        76.0
mcrc_promedio             0.0        76.0
mcrc_std                  0.0        76.0
mra_max                   0.0        76.0
mra_min                   0.0        76.0
mra_promedio              0.0        76.0
mra_std                   0.0        76.0
msi_max                   0.0        76.0
msi_min                   0.0        76.0
msi_promedio              0.0        76.0
msi_std                   0.0        76.0
nddi_max                  0.0        76.0
nddi_min                  0.0        76.0
nddi_promedio             0.0        76.0
nddi_std                  0.0        76.0
ndsvi_max                 0.0        76.0
ndsvi_min                 0.0        76.0
ndsvi_promedio            0.0        76.0
ndsvi_std                 0.0        76.0
ndti_max                  0.0        76.0
ndti_min                  0.0        76.0
ndti_promedio             0.0        76.0
ndti_std                  0.0        76.0
ndvi_max                  0.0        76.0
ndvi_min                  0.0        76.0
ndvi_promedio             0.0        76.0
ndvi_std                  0.0        76.0
ndwi_max                  0.0        76.0
ndwi_min                  0.0        76.0
ndwi_promedio             0.0        76.0
ndwi_std                  0.0        76.0
porcentaje_nubosidad     93.7       100.0
savi_max                  0.0        76.0
savi_min                  0.0        76.0
savi_promedio             0.0        76.0
savi_std                  0.0        76.0
srndi_max                 0.0        76.0
srndi_min                 0.0        76.0
srndi_promedio            0.0        76.0
srndi_std                 0.0        76.0
sti_max                   0.0        76.0
sti_min                   0.0        76.0
sti_promedio              0.0        76.0
sti_std                   0.0        76.0
vi6t_max                 63.9         0.0
vi6t_min                 63.9         0.0
vi6t_promedio            63.9         0.0
vi6t_std                 63.9         0.0

=== VARIABLES CON DATOS EXCLUSIVOS DE CADA SENSOR ===

Landsat:
['vi6t_promedio', 'vi6t_std', 'vi6t_max', 'vi6t_min', 'porcentaje_nubosidad']

Sentinel-2:
['ndvi_promedio', 'ndvi_std', 'ndvi_max', 'ndvi_min', 'evi_promedio', 'evi_std', 'evi_max', 'evi_min', 'crc_promedio', 'crc_std', 'crc_max', 'crc_min', 'mcrc_promedio', 'mcrc_std', 'mcrc_max', 'mcrc_min', 'ndsvi_promedio', 'ndsvi_std', 'ndsvi_max', 'ndsvi_min', 'srndi_promedio', 'srndi_std', 'srndi_max', 'srndi_min', 'mra_promedio', 'mra_std', 'mra_max', 'mra_min', 'lai_promedio', 'lai_std', 'lai_max', 'lai_min', 'fapar_promedio', 'fapar_std', 'fapar_max', 'fapar_min', 'savi_promedio', 'savi_std', 'savi_max', 'savi_min', 'ndti_promedio', 'ndti_std', 'ndti_max', 'ndti_min', 'sti_promedio', 'sti_std', 'sti_max', 'sti_min', 'ndwi_promedio', 'ndwi_std', 'ndwi_max', 'ndwi_min', 'endwi_promedio', 'endwi_std', 'endwi_max', 'endwi_min', 'msi_promedio', 'msi_std', 'msi_max', 'msi_min', 'emsi_promedio', 'emsi_std', 'emsi_max', 'emsi_min', 'dswi2_promedio', 'dswi2_std', 'dswi2_max', 'dswi2_min', 'dswi3_promedio', 'dswi3_std', 'dswi3_max', 'dswi3_min', 'dswi4_promedio', 'dswi4_std', 'dswi4_max', 'dswi4_min', 'dswi5_promedio', 'dswi5_std', 'dswi5_max', 'dswi5_min', 'nddi_promedio', 'nddi_std', 'nddi_max', 'nddi_min', 'enddi_promedio', 'enddi_std', 'enddi_max', 'enddi_min', 'porcentaje_nubosidad']

=== VARIABLES COMPLETAMENTE VACÍAS ===

Landsat: ['ndvi_promedio', 'ndvi_std', 'ndvi_max', 'ndvi_min', 'evi_promedio', 'evi_std', 'evi_max', 'evi_min', 'crc_promedio', 'crc_std', 'crc_max', 'crc_min', 'mcrc_promedio', 'mcrc_std', 'mcrc_max', 'mcrc_min', 'ndsvi_promedio', 'ndsvi_std', 'ndsvi_max', 'ndsvi_min', 'srndi_promedio', 'srndi_std', 'srndi_max', 'srndi_min', 'mra_promedio', 'mra_std', 'mra_max', 'mra_min', 'lai_promedio', 'lai_std', 'lai_max', 'lai_min', 'fapar_promedio', 'fapar_std', 'fapar_max', 'fapar_min', 'savi_promedio', 'savi_std', 'savi_max', 'savi_min', 'ndti_promedio', 'ndti_std', 'ndti_max', 'ndti_min', 'sti_promedio', 'sti_std', 'sti_max', 'sti_min', 'ndwi_promedio', 'ndwi_std', 'ndwi_max', 'ndwi_min', 'endwi_promedio', 'endwi_std', 'endwi_max', 'endwi_min', 'msi_promedio', 'msi_std', 'msi_max', 'msi_min', 'emsi_promedio', 'emsi_std', 'emsi_max', 'emsi_min', 'dswi2_promedio', 'dswi2_std', 'dswi2_max', 'dswi2_min', 'dswi3_promedio', 'dswi3_std', 'dswi3_max', 'dswi3_min', 'dswi4_promedio', 'dswi4_std', 'dswi4_max', 'dswi4_min', 'dswi5_promedio', 'dswi5_std', 'dswi5_max', 'dswi5_min', 'nddi_promedio', 'nddi_std', 'nddi_max', 'nddi_min', 'enddi_promedio', 'enddi_std', 'enddi_max', 'enddi_min']

Sentinel-2: ['vi6t_promedio', 'vi6t_std', 'vi6t_max', 'vi6t_min']

Auditoría terminada; no se modificaron los datos originales.

In [31]:

# CELDA 28 — INVENTARIO DETALLADO DE RÁSTERES ORIGINALES

from pathlib import Path
from collections import defaultdict
import rasterio

raw_dir = Path(ROOT) / "data" / "raw"

rasteres = sorted(
    p for p in raw_dir.rglob("*")
    if p.is_file() and p.suffix.lower() in {".tif", ".tiff"}
)

grupos = defaultdict(list)

for p in rasteres:
    nombre = p.name.upper()

    if nombre.startswith(("PREC_", "PRECIP_")):
        grupo = "PRECIPITACION"
    elif nombre.startswith("TMAX_"):
        grupo = "TEMPERATURA_MAXIMA"
    elif nombre.startswith("TMIN_"):
        grupo = "TEMPERATURA_MINIMA"
    else:
        grupo = "OTROS"

    grupos[grupo].append(p)

print("=== CANTIDAD DE RÁSTERES POR GRUPO ===")
for grupo, archivos in sorted(grupos.items()):
    print(f"{grupo}: {len(archivos)}")

print("\n=== MUESTRA DE NOMBRES DE ARCHIVO ===")
for grupo, archivos in sorted(grupos.items()):
    print(f"\n{grupo}")
    for p in archivos[:10]:
        print(" ", p.relative_to(raw_dir))

print("\n=== METADATOS DE LOS PRIMEROS RÁSTERES ===")
for grupo, archivos in sorted(grupos.items()):
    if not archivos:
        continue

    p = archivos[0]

    with rasterio.open(p) as src:
        print(f"\nArchivo: {p.relative_to(raw_dir)}")
        print("CRS:", src.crs)
        print("Dimensiones:", src.width, "x", src.height)
        print("Bandas:", src.count)
        print("Tipo de datos:", src.dtypes)
        print("NoData:", src.nodata)
        print("Resolución:", src.res)
        print("Extensión:", src.bounds)

print("\nInventario terminado; no se modificaron los archivos.")

=== CANTIDAD DE RÁSTERES POR GRUPO ===
OTROS: 2
PRECIPITACION: 48
TEMPERATURA_MAXIMA: 48
TEMPERATURA_MINIMA: 48

=== MUESTRA DE NOMBRES DE ARCHIVO ===

OTROS
  topography\Elevacion_INEGI_CEM4_120m.tif
  topography\Pendiente_INEGI_CEM4_120m_grados.tif

PRECIPITACION
  climate\precipitation\2022\PREC_2022_01.tif
  climate\precipitation\2022\PREC_2022_02.tif
  climate\precipitation\2022\PREC_2022_03.tif
  climate\precipitation\2022\PREC_2022_04.tif
  climate\precipitation\2022\PREC_2022_05.tif
  climate\precipitation\2022\PREC_2022_06.tif
  climate\precipitation\2022\PREC_2022_07.tif
  climate\precipitation\2022\PREC_2022_08.tif
  climate\precipitation\2022\PREC_2022_09.tif
  climate\precipitation\2022\PREC_2022_10.tif

TEMPERATURA_MAXIMA
  climate\temperature\Tmax\2022\Tmax_2022_01.tif
  climate\temperature\Tmax\2022\Tmax_2022_02.tif
  climate\temperature\Tmax\2022\Tmax_2022_03.tif
  climate\temperature\Tmax\2022\Tmax_2022_04.tif
  climate\temperature\Tmax\2022\Tmax_2022_05.tif
  climate\temperature\Tmax\2022\Tmax_2022_06.tif
  climate\temperature\Tmax\2022\Tmax_2022_07.tif
  climate\temperature\Tmax\2022\Tmax_2022_08.tif
  climate\temperature\Tmax\2022\Tmax_2022_09.tif
  climate\temperature\Tmax\2022\Tmax_2022_10.tif

TEMPERATURA_MINIMA
  climate\temperature\Tmin\2022\Tmin_2022_01.tif
  climate\temperature\Tmin\2022\Tmin_2022_02.tif
  climate\temperature\Tmin\2022\Tmin_2022_03.tif
  climate\temperature\Tmin\2022\Tmin_2022_04.tif
  climate\temperature\Tmin\2022\Tmin_2022_05.tif
  climate\temperature\Tmin\2022\Tmin_2022_06.tif
  climate\temperature\Tmin\2022\Tmin_2022_07.tif
  climate\temperature\Tmin\2022\Tmin_2022_08.tif
  climate\temperature\Tmin\2022\Tmin_2022_09.tif
  climate\temperature\Tmin\2022\Tmin_2022_10.tif

=== METADATOS DE LOS PRIMEROS RÁSTERES ===

Archivo: topography\Elevacion_INEGI_CEM4_120m.tif
CRS: EPSG:6372
Dimensiones: 2900 x 3362
Bandas: 1
Tipo de datos: ('float32',)
NoData: -9999.0
Resolución: (120.0, 120.0)
Extensión: BoundingBox(left=2715840.0, bottom=650400.0, right=3063840.0, top=1053840.0)

Archivo: climate\precipitation\2022\PREC_2022_01.tif
CRS: EPSG:4326
Dimensiones: 65 x 72
Bandas: 1
Tipo de datos: ('float32',)
NoData: -9999.0
Resolución: (0.05000000074505806, 0.05000000074505806)
Extensión: BoundingBox(left=-99.94999880716205, bottom=17.79999952018261, right=-96.69999875873327, top=21.39999957382679)

Archivo: climate\temperature\Tmax\2022\Tmax_2022_01.tif
CRS: EPSG:4326
Dimensiones: 65 x 72
Bandas: 1
Tipo de datos: ('float32',)
NoData: -9999.0
Resolución: (0.05000000074505806, 0.05000000074505806)
Extensión: BoundingBox(left=-99.94999880716205, bottom=17.799999222159386, right=-96.69999875873327, top=21.399999275803566)

Archivo: climate\temperature\Tmin\2022\Tmin_2022_01.tif
CRS: EPSG:4326
Dimensiones: 65 x 72
Bandas: 1
Tipo de datos: ('float32',)
NoData: -9999.0
Resolución: (0.05000000074505806, 0.05000000074505806)
Extensión: BoundingBox(left=-99.94999880716205, bottom=17.799999222159386, right=-96.69999875873327, top=21.399999275803566)

Inventario terminado; no se modificaron los archivos.

In [32]:

# CELDA 29 — AUDITORÍA DE LAS VARIABLES DEL MODELO RF124

from pathlib import Path
import json
import joblib

model_path = (
    Path(ROOT) / "models" / "reconstruccion_rf124_leaf16"
    / "RF124_leaf16_final.joblib"
)

metadata_path = (
    Path(ROOT) / "models" / "reconstruccion_rf124_leaf16"
    / "metadata.json"
)

if not model_path.exists():
    raise FileNotFoundError(f"No se encontró el modelo: {model_path}")

modelo = joblib.load(model_path)

print("=== MODELO ===")
print("Tipo:", type(modelo).__name__)

# Recuperar nombres de variables, si el estimador los conserva.
feature_names = getattr(modelo, "feature_names_in_", None)

if feature_names is None and hasattr(modelo, "named_steps"):
    for nombre, paso in reversed(list(modelo.named_steps.items())):
        feature_names = getattr(paso, "feature_names_in_", None)
        if feature_names is not None:
            print("Variables recuperadas del paso:", nombre)
            break

if feature_names is None:
    print(
        "\nEl objeto no conserva feature_names_in_. "
        "Revisaremos sus metadatos o el notebook de reconstrucción."
    )
else:
    feature_names = list(feature_names)
    print("Número de variables:", len(feature_names))

    print("\n=== LISTA COMPLETA DE VARIABLES ===")
    for i, nombre in enumerate(feature_names, start=1):
        print(f"{i:03d}. {nombre}")

    # Clasificación preliminar por nombre; no sustituye una revisión.
    print("\n=== CLASIFICACIÓN PRELIMINAR ===")

    grupos = {
        "CLIMÁTICAS": [],
        "TOPOGRÁFICAS": [],
        "ESPECTRALES / TEMPORALES": [],
        "OTRAS / POR CLASIFICAR": [],
    }

    for nombre in feature_names:
        n = nombre.lower()

        if any(x in n for x in [
            "prec", "precip", "tmax", "tmin", "temperatura",
            "rain", "climate", "clima"
        ]):
            grupos["CLIMÁTICAS"].append(nombre)
        elif any(x in n for x in [
            "elev", "altitud", "pendiente", "slope", "dem", "topo"
        ]):
            grupos["TOPOGRÁFICAS"].append(nombre)
        elif any(x in n for x in [
            "ndvi", "evi", "lai", "savi", "msavi", "vi6t",
            "ndwi", "ndti", "fapar", "dswi", "mcrc", "nddi",
            "srndi", "landsat", "sentinel", "planet"
        ]):
            grupos["ESPECTRALES / TEMPORALES"].append(nombre)
        else:
            grupos["OTRAS / POR CLASIFICAR"].append(nombre)

    for grupo, nombres in grupos.items():
        print(f"\n{grupo}: {len(nombres)}")
        for nombre in nombres:
            print("  ", nombre)

if metadata_path.exists():
    print("\n=== METADATOS DEL MODELO ===")
    with open(metadata_path, "r", encoding="utf-8") as f:
        metadata = json.load(f)
    print(json.dumps(metadata, ensure_ascii=False, indent=2))
else:
    print("\nNo existe metadata.json.")

=== MODELO ===
Tipo: RandomForestRegressor
Número de variables: 124

=== LISTA COMPLETA DE VARIABLES ===
001. ndvi_promedio_inicial
002. ndvi_std_inicial
003. ndvi_max_inicial
004. ndvi_min_inicial
005. evi_promedio_inicial
006. evi_std_inicial
007. evi_max_inicial
008. evi_min_inicial
009. lai_promedio_inicial
010. lai_std_inicial
011. lai_max_inicial
012. lai_min_inicial
013. msavi_promedio_inicial
014. msavi_std_inicial
015. msavi_max_inicial
016. msavi_min_inicial
017. observaciones_inicial
018. ndvi_promedio_intermedia
019. ndvi_std_intermedia
020. ndvi_max_intermedia
021. ndvi_min_intermedia
022. evi_promedio_intermedia
023. evi_std_intermedia
024. evi_max_intermedia
025. evi_min_intermedia
026. lai_promedio_intermedia
027. lai_std_intermedia
028. lai_max_intermedia
029. lai_min_intermedia
030. msavi_promedio_intermedia
031. msavi_std_intermedia
032. msavi_max_intermedia
033. msavi_min_intermedia
034. observaciones_intermedia
035. ndvi_promedio_tardia
036. ndvi_std_tardia
037. ndvi_max_tardia
038. ndvi_min_tardia
039. evi_promedio_tardia
040. evi_std_tardia
041. evi_max_tardia
042. evi_min_tardia
043. lai_promedio_tardia
044. lai_std_tardia
045. lai_max_tardia
046. lai_min_tardia
047. msavi_promedio_tardia
048. msavi_std_tardia
049. msavi_max_tardia
050. msavi_min_tardia
051. observaciones_tardia
052. precip_mm_m04
053. precip_mm_m05
054. precip_mm_m06
055. precip_mm_m07
056. precip_mm_m08
057. precip_mm_m09
058. precip_mm_m10
059. tmax_c_m04
060. tmax_c_m05
061. tmax_c_m06
062. tmax_c_m07
063. tmax_c_m08
064. tmax_c_m09
065. tmax_c_m10
066. tmin_c_m04
067. tmin_c_m05
068. tmin_c_m06
069. tmin_c_m07
070. tmin_c_m08
071. tmin_c_m09
072. tmin_c_m10
073. tmedia_c_m04
074. tmedia_c_m05
075. tmedia_c_m06
076. tmedia_c_m07
077. tmedia_c_m08
078. tmedia_c_m09
079. tmedia_c_m10
080. precip_suma_temprano
081. precip_suma_intermedio
082. precip_suma_tardio
083. precip_suma_temporada
084. precip_media_temprano
085. precip_media_intermedio
086. precip_media_tardio
087. precip_media_temporada
088. precip_std_temprano
089. precip_std_intermedio
090. precip_std_tardio
091. precip_std_temporada
092. tmax_media_temprano
093. tmax_media_intermedio
094. tmax_media_tardio
095. tmax_media_temporada
096. tmax_std_temprano
097. tmax_std_intermedio
098. tmax_std_tardio
099. tmax_std_temporada
100. tmax_min_temprano
101. tmax_min_intermedio
102. tmax_min_tardio
103. tmax_min_temporada
104. tmax_max_temprano
105. tmax_max_intermedio
106. tmax_max_tardio
107. tmax_max_temporada
108. tmin_media_temprano
109. tmin_media_intermedio
110. tmin_media_tardio
111. tmin_media_temporada
112. tmin_std_temprano
113. tmin_std_intermedio
114. tmin_std_tardio
115. tmin_std_temporada
116. tmin_min_temprano
117. tmin_min_intermedio
118. tmin_min_tardio
119. tmin_min_temporada
120. tmin_max_temprano
121. tmin_max_intermedio
122. tmin_max_tardio
123. tmin_max_temporada
124. AREA_HA

=== CLASIFICACIÓN PRELIMINAR ===

CLIMÁTICAS: 65
   precip_mm_m04
   precip_mm_m05
   precip_mm_m06
   precip_mm_m07
   precip_mm_m08
   precip_mm_m09
   precip_mm_m10
   tmax_c_m04
   tmax_c_m05
   tmax_c_m06
   tmax_c_m07
   tmax_c_m08
   tmax_c_m09
   tmax_c_m10
   tmin_c_m04
   tmin_c_m05
   tmin_c_m06
   tmin_c_m07
   tmin_c_m08
   tmin_c_m09
   tmin_c_m10
   precip_suma_temprano
   precip_suma_intermedio
   precip_suma_tardio
   precip_suma_temporada
   precip_media_temprano
   precip_media_intermedio
   precip_media_tardio
   precip_media_temporada
   precip_std_temprano
   precip_std_intermedio
   precip_std_tardio
   precip_std_temporada
   tmax_media_temprano
   tmax_media_intermedio
   tmax_media_tardio
   tmax_media_temporada
   tmax_std_temprano
   tmax_std_intermedio
   tmax_std_tardio
   tmax_std_temporada
   tmax_min_temprano
   tmax_min_intermedio
   tmax_min_tardio
   tmax_min_temporada
   tmax_max_temprano
   tmax_max_intermedio
   tmax_max_tardio
   tmax_max_temporada
   tmin_media_temprano
   tmin_media_intermedio
   tmin_media_tardio
   tmin_media_temporada
   tmin_std_temprano
   tmin_std_intermedio
   tmin_std_tardio
   tmin_std_temporada
   tmin_min_temprano
   tmin_min_intermedio
   tmin_min_tardio
   tmin_min_temporada
   tmin_max_temprano
   tmin_max_intermedio
   tmin_max_tardio
   tmin_max_temporada

TOPOGRÁFICAS: 0

ESPECTRALES / TEMPORALES: 48
   ndvi_promedio_inicial
   ndvi_std_inicial
   ndvi_max_inicial
   ndvi_min_inicial
   evi_promedio_inicial
   evi_std_inicial
   evi_max_inicial
   evi_min_inicial
   lai_promedio_inicial
   lai_std_inicial
   lai_max_inicial
   lai_min_inicial
   msavi_promedio_inicial
   msavi_std_inicial
   msavi_max_inicial
   msavi_min_inicial
   ndvi_promedio_intermedia
   ndvi_std_intermedia
   ndvi_max_intermedia
   ndvi_min_intermedia
   evi_promedio_intermedia
   evi_std_intermedia
   evi_max_intermedia
   evi_min_intermedia
   lai_promedio_intermedia
   lai_std_intermedia
   lai_max_intermedia
   lai_min_intermedia
   msavi_promedio_intermedia
   msavi_std_intermedia
   msavi_max_intermedia
   msavi_min_intermedia
   ndvi_promedio_tardia
   ndvi_std_tardia
   ndvi_max_tardia
   ndvi_min_tardia
   evi_promedio_tardia
   evi_std_tardia
   evi_max_tardia
   evi_min_tardia
   lai_promedio_tardia
   lai_std_tardia
   lai_max_tardia
   lai_min_tardia
   msavi_promedio_tardia
   msavi_std_tardia
   msavi_max_tardia
   msavi_min_tardia

OTRAS / POR CLASIFICAR: 11
   observaciones_inicial
   observaciones_intermedia
   observaciones_tardia
   tmedia_c_m04
   tmedia_c_m05
   tmedia_c_m06
   tmedia_c_m07
   tmedia_c_m08
   tmedia_c_m09
   tmedia_c_m10
   AREA_HA

=== METADATOS DEL MODELO ===
{
  "modelo": "RF124_leaf16",
  "n_variables": 124,
  "n_entrenamiento": 138,
  "n_prediccion": 59,
  "n_estimators": 500,
  "min_samples_leaf": 16,
  "max_features": 1.0,
  "random_state": 2026,
  "variables": [
    "ndvi_promedio_inicial",
    "ndvi_std_inicial",
    "ndvi_max_inicial",
    "ndvi_min_inicial",
    "evi_promedio_inicial",
    "evi_std_inicial",
    "evi_max_inicial",
    "evi_min_inicial",
    "lai_promedio_inicial",
    "lai_std_inicial",
    "lai_max_inicial",
    "lai_min_inicial",
    "msavi_promedio_inicial",
    "msavi_std_inicial",
    "msavi_max_inicial",
    "msavi_min_inicial",
    "observaciones_inicial",
    "ndvi_promedio_intermedia",
    "ndvi_std_intermedia",
    "ndvi_max_intermedia",
    "ndvi_min_intermedia",
    "evi_promedio_intermedia",
    "evi_std_intermedia",
    "evi_max_intermedia",
    "evi_min_intermedia",
    "lai_promedio_intermedia",
    "lai_std_intermedia",
    "lai_max_intermedia",
    "lai_min_intermedia",
    "msavi_promedio_intermedia",
    "msavi_std_intermedia",
    "msavi_max_intermedia",
    "msavi_min_intermedia",
    "observaciones_intermedia",
    "ndvi_promedio_tardia",
    "ndvi_std_tardia",
    "ndvi_max_tardia",
    "ndvi_min_tardia",
    "evi_promedio_tardia",
    "evi_std_tardia",
    "evi_max_tardia",
    "evi_min_tardia",
    "lai_promedio_tardia",
    "lai_std_tardia",
    "lai_max_tardia",
    "lai_min_tardia",
    "msavi_promedio_tardia",
    "msavi_std_tardia",
    "msavi_max_tardia",
    "msavi_min_tardia",
    "observaciones_tardia",
    "precip_mm_m04",
    "precip_mm_m05",
    "precip_mm_m06",
    "precip_mm_m07",
    "precip_mm_m08",
    "precip_mm_m09",
    "precip_mm_m10",
    "tmax_c_m04",
    "tmax_c_m05",
    "tmax_c_m06",
    "tmax_c_m07",
    "tmax_c_m08",
    "tmax_c_m09",
    "tmax_c_m10",
    "tmin_c_m04",
    "tmin_c_m05",
    "tmin_c_m06",
    "tmin_c_m07",
    "tmin_c_m08",
    "tmin_c_m09",
    "tmin_c_m10",
    "tmedia_c_m04",
    "tmedia_c_m05",
    "tmedia_c_m06",
    "tmedia_c_m07",
    "tmedia_c_m08",
    "tmedia_c_m09",
    "tmedia_c_m10",
    "precip_suma_temprano",
    "precip_suma_intermedio",
    "precip_suma_tardio",
    "precip_suma_temporada",
    "precip_media_temprano",
    "precip_media_intermedio",
    "precip_media_tardio",
    "precip_media_temporada",
    "precip_std_temprano",
    "precip_std_intermedio",
    "precip_std_tardio",
    "precip_std_temporada",
    "tmax_media_temprano",
    "tmax_media_intermedio",
    "tmax_media_tardio",
    "tmax_media_temporada",
    "tmax_std_temprano",
    "tmax_std_intermedio",
    "tmax_std_tardio",
    "tmax_std_temporada",
    "tmax_min_temprano",
    "tmax_min_intermedio",
    "tmax_min_tardio",
    "tmax_min_temporada",
    "tmax_max_temprano",
    "tmax_max_intermedio",
    "tmax_max_tardio",
    "tmax_max_temporada",
    "tmin_media_temprano",
    "tmin_media_intermedio",
    "tmin_media_tardio",
    "tmin_media_temporada",
    "tmin_std_temprano",
    "tmin_std_intermedio",
    "tmin_std_tardio",
    "tmin_std_temporada",
    "tmin_min_temprano",
    "tmin_min_intermedio",
    "tmin_min_tardio",
    "tmin_min_temporada",
    "tmin_max_temprano",
    "tmin_max_intermedio",
    "tmin_max_tardio",
    "tmin_max_temporada",
    "AREA_HA"
  ],
  "nota": "Modelo reentrenado con todas las parcelas etiquetadas; no equivale a un archivo histórico recuperado."
}